use sha2::{Digest as ShaDigest, Sha256};

#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub struct AdmissionAuthority {
    pub artifact_name: &'static str,
    pub contract_id: &'static str,
    pub admits: &'static str,
}

#[derive(Debug, Clone, Eq, PartialEq)]
pub enum ContractAuthorityError {
    UnknownContract(String),
    UnknownArtifact(String),
}

impl std::fmt::Display for ContractAuthorityError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::UnknownContract(contract) => {
                write!(formatter, "unknown contract authority: {contract}")
            }
            Self::UnknownArtifact(artifact) => {
                write!(formatter, "unknown admission artifact: {artifact}")
            }
        }
    }
}

impl std::error::Error for ContractAuthorityError {}

#[must_use]
pub fn admission_authorities() -> Vec<AdmissionAuthority> {
    kernel::generated::ADMISSION_CONTRACTS
        .iter()
        .map(|(artifact_name, contract_id, admits)| AdmissionAuthority {
            artifact_name,
            contract_id,
            admits,
        })
        .collect()
}

pub fn by_contract(contract_id: &str) -> Result<AdmissionAuthority, ContractAuthorityError> {
    kernel::generated::ADMISSION_CONTRACTS
        .iter()
        .find(|(_, schema, _)| *schema == contract_id)
        .map(|(artifact_name, schema, admits)| AdmissionAuthority {
            artifact_name,
            contract_id: schema,
            admits,
        })
        .ok_or_else(|| ContractAuthorityError::UnknownContract(contract_id.to_owned()))
}

pub fn by_artifact(artifact_name: &str) -> Result<AdmissionAuthority, ContractAuthorityError> {
    kernel::generated::ADMISSION_CONTRACTS
        .iter()
        .find(|(name, _, _)| *name == artifact_name)
        .map(|(name, schema, admits)| AdmissionAuthority {
            artifact_name: name,
            contract_id: schema,
            admits,
        })
        .ok_or_else(|| ContractAuthorityError::UnknownArtifact(artifact_name.to_owned()))
}

pub fn contract_digest(contract_id: &str) -> Result<String, ContractAuthorityError> {
    let admits = match by_contract(contract_id) {
        Ok(authority) => authority.admits,
        Err(ContractAuthorityError::UnknownContract(_))
            if matches!(
                contract_id,
                "autopilot.delivery_result.v2"
                    | "autopilot.validation_result.v2"
                    | "autopilot.validation_result.v3"
            ) =>
        {
            contract_id
        }
        Err(error) => return Err(error),
    };
    Ok(sha256_hex(format!("{contract_id}\0{admits}").as_bytes()))
}

pub fn render_contract_authority(contract_id: &str) -> Result<String, ContractAuthorityError> {
    let authority = by_contract(contract_id)?;
    let digest = contract_digest(contract_id)?;
    Ok(format!(
        "Package-generated admission authority for {contract_id}\ncontract_id: {contract_id}\ncontract_digest: {digest}\nadmits:\n{}",
        authority.admits
    ))
}

pub fn render_generated_prompt_by_artifact(
    artifact_name: &str,
) -> Result<String, ContractAuthorityError> {
    let authority = by_artifact(artifact_name)?;
    Ok(format!(
        "<!-- @generated by codegen -->\n# {artifact_name}\n\n{}\n",
        authority.admits
    ))
}

fn sha256_hex(data: &[u8]) -> String {
    Sha256::digest(data)
        .iter()
        .fold(String::new(), |mut out, byte| {
            out.push_str(&format!("{byte:02x}"));
            out
        })
}
