import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

interface CapsuleExport {
  readonly capsuleName: string;
  readonly exportName: string;
  readonly sourceFile: string;
}

const modulePolicyRoot = dirname(fileURLToPath(import.meta.url));
const moduleParent = dirname(modulePolicyRoot);
const nextRoot = basename(moduleParent) === "dist-policy" ? dirname(moduleParent) : moduleParent;

function compareText(left: string, right: string): number {
  if (left < right) {
    return -1;
  }
  return left > right ? 1 : 0;
}

function discoverCapsules(directory: string): readonly CapsuleExport[] {
  const discovered: CapsuleExport[] = [];
  const files = readdirSync(directory)
    .filter((file) => file.endsWith(".capsule.ts"))
    .sort(compareText);
  const declaration = /export const (\w+Capsule)\s*=\s*(?:defineCapsule|defineIntentCapsule|makeToolResultCapsule)\(\s*"([^"]+)"/g;
  for (const file of files) {
    const source = readFileSync(join(directory, file), "utf8");
    for (const match of source.matchAll(declaration)) {
      const exportName = match[1];
      const capsuleName = match[2];
      if (exportName !== undefined && capsuleName !== undefined) {
        discovered.push({ capsuleName, exportName, sourceFile: file });
      }
    }
  }
  return Object.freeze(discovered.sort((left, right) => compareText(left.capsuleName, right.capsuleName)));
}

function generatedSource(
  aggregateName: string,
  capsules: readonly CapsuleExport[],
): string {
  const aggregateTypeImport = aggregateName === "protocolCapsules"
    ? 'import type { AggregateCapsule } from "./schema.js";'
    : 'import type { AggregateCapsule } from "../../authority/protocol/schema.js";';
  const imports = capsules
    .map((capsule) => `import { ${capsule.exportName} } from "./${capsule.sourceFile.replace(/\.ts$/, ".js")}";`)
    .join("\n");
  const entries = capsules
    .map((capsule) => `  ${capsule.exportName},`)
    .join("\n");
  const exports = capsules
    .map((capsule) => capsule.exportName)
    .join(",\n  ");
  return `/* GENERATED by policy-root/generate-aggregates.ts. DO NOT EDIT. */\n${aggregateTypeImport}\n${imports}\n\nexport {\n  ${exports},\n};\n\nexport const ${aggregateName}: readonly AggregateCapsule[] = Object.freeze([\n${entries}\n]);\n`;
}

function checkOrWrite(target: string, expected: string, checkOnly: boolean): void {
  let actual = "";
  try {
    actual = readFileSync(target, "utf8");
  } catch {
    actual = "";
  }
  if (actual === expected) {
    return;
  }
  if (checkOnly) {
    process.stderr.write(`generated aggregate is stale: ${relative(nextRoot, target)}\n`);
    process.exitCode = 1;
    return;
  }
  writeFileSync(target, expected, "utf8");
}

export function generateAggregates(checkOnly: boolean): void {
  const protocolDirectory = join(nextRoot, "authority", "protocol");
  const contractsDirectory = join(nextRoot, "ports", "contracts");
  const protocolCapsules = discoverCapsules(protocolDirectory);
  const contractCapsules = discoverCapsules(contractsDirectory);
  if (protocolCapsules.length !== 13) {
    process.stderr.write(`expected 13 protocol capsules, found ${String(protocolCapsules.length)}\n`);
    process.exitCode = 1;
  }
  if (contractCapsules.length !== 12) {
    process.stderr.write(`expected 12 port capsules, found ${String(contractCapsules.length)}\n`);
    process.exitCode = 1;
  }
  checkOrWrite(
    join(protocolDirectory, "aggregate.generated.ts"),
    generatedSource("protocolCapsules", protocolCapsules),
    checkOnly,
  );
  checkOrWrite(
    join(contractsDirectory, "aggregate.generated.ts"),
    generatedSource("portContractCapsules", contractCapsules),
    checkOnly,
  );
}

const invokedFile = process.argv[1] === undefined ? "" : basename(process.argv[1]);
if (invokedFile === "generate-aggregates.ts" || invokedFile === "generate-aggregates.js") {
  const argument = process.argv[2];
  if (argument !== undefined && argument !== "--check") {
    process.stderr.write("generate-aggregates accepts only --check\n");
    process.exitCode = 2;
  } else {
    generateAggregates(argument === "--check");
  }
}
