use std::fs;
use std::path::Path;

use assert_cmd::Command;
use predicates::prelude::*;
use tempfile::TempDir;

fn fixture() -> TempDir {
    let temp = tempfile::tempdir().expect("tempdir");
    let data_dir = temp.path().join("data");
    fs::create_dir_all(&data_dir).expect("create data dir");
    for name in [
        "contracts.kdl",
        "seam.kdl",
        "host-runtime.kdl",
        "pi-rpc.kdl",
        "recovery.kdl",
    ] {
        fs::copy(
            Path::new(env!("CARGO_MANIFEST_DIR")).join(format!("../data/{name}")),
            data_dir.join(name),
        )
        .expect("copy data");
    }
    temp
}

fn codegen_command() -> Command {
    Command::cargo_bin("codegen").expect("codegen binary")
}

#[test]
fn check_catches_a_hand_edit_and_recovers() {
    let temp = fixture();

    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    codegen_command()
        .current_dir(temp.path())
        .arg("--check")
        .assert()
        .success();

    let generated = temp.path().join("drivers/src/generated/tables.rs");
    let mut content = fs::read_to_string(&generated).expect("read generated file");
    content.push_str("// hand edit\n");
    fs::write(&generated, content).expect("mutate generated file");

    codegen_command()
        .current_dir(temp.path())
        .arg("--check")
        .assert()
        .code(1)
        .stderr(predicates::str::contains("first differing line"));

    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    codegen_command()
        .current_dir(temp.path())
        .arg("--check")
        .assert()
        .success();
}

#[test]
fn pi_rpc_generation_and_mutations_fail_loudly() {
    let temp = fixture();
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    let generated = temp.path().join("drivers/src/generated/pi_rpc.rs");
    let content = fs::read_to_string(&generated).expect("read pi rpc");
    assert!(content.contains("ENV_DENY"));
    assert!(content.contains("EventOrder"));
    fs::write(&generated, format!("{content}\n// drift\n")).expect("mutate generated");
    codegen_command()
        .current_dir(temp.path())
        .arg("--check")
        .assert()
        .code(1)
        .stderr(predicate::str::contains("pi_rpc.rs"));
    let temp = fixture();
    let path = temp.path().join("data/pi-rpc.kdl");
    let content = fs::read_to_string(&path).expect("read pi rpc kdl");
    fs::write(&path, content.replace("env_deny \"OPENAI_API_KEY\"\n", ""))
        .expect("mutate pi rpc kdl");
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .code(2)
        .stderr(predicate::str::contains("pi-rpc env_deny row drift"));
}

#[test]
fn unknown_kdl_node_is_rejected() {
    let temp = fixture();
    let contracts = temp.path().join("data/contracts.kdl");
    let mut content = fs::read_to_string(&contracts).expect("read contracts");
    content.push_str("\nbogus_node \"not allowed\"\n");
    fs::write(&contracts, content).expect("write bogus contracts");

    codegen_command()
        .current_dir(temp.path())
        .assert()
        .code(2)
        .stderr(
            predicates::str::contains("unknown top-level node `bogus_node`")
                .and(predicates::str::contains("line")),
        );
}

#[test]
fn frame_validation_output_is_generated_and_drift_checked() {
    let temp = fixture();
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    let generated = temp.path().join("src/generated/frame-validation.ts");
    let content = fs::read_to_string(&generated).expect("read frame validation");
    assert!(content.starts_with("// @generated by codegen"));
    assert!(content.contains("FRAME_VALIDATION_DESCRIPTORS"));
    assert!(content.contains("../frame-validation-runtime.ts"));
    assert!(content.contains("spawn-attested"));
    assert!(content.contains("list_constraints"));

    fs::write(&generated, format!("{content}\n// drift\n")).expect("mutate frame validation");
    codegen_command()
        .current_dir(temp.path())
        .arg("--check")
        .assert()
        .code(1)
        .stderr(predicates::str::contains("frame-validation.ts"));
}

#[test]
fn frame_validation_check_catches_contracts_and_seam_ts_drift() {
    let temp = fixture();
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    let contracts = temp.path().join("data/contracts.kdl");
    let content = fs::read_to_string(&contracts).expect("read contracts");
    fs::write(
        &contracts,
        content.replace(
            "field \"line\" type=\"string\" required=#true",
            "field \"line_extra\" type=\"string\" required=#true",
        ),
    )
    .expect("mutate contracts");
    codegen_command()
        .current_dir(temp.path())
        .arg("--check")
        .assert()
        .code(1)
        .stderr(predicates::str::contains("generated output drift"));

    let temp = fixture();
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    let seam = temp.path().join("data/seam.kdl");
    let content = fs::read_to_string(&seam).expect("read seam");
    fs::write(
        &seam,
        content.replace("effect=\"log\"", "effect=\"log-mutated\""),
    )
    .expect("mutate seam");
    codegen_command()
        .current_dir(temp.path())
        .arg("--check")
        .assert()
        .code(1)
        .stderr(predicates::str::contains("generated output drift"));
}

#[test]
fn child_extension_output_is_wrapper_and_drift_checked() {
    let temp = fixture();
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    let generated_path = temp.path().join("src/generated/child-extension.ts");
    let content = fs::read_to_string(&generated_path).expect("read child extension");
    assert!(content.starts_with("// @generated by codegen"));
    assert!(content.contains("../../child-runtime/child-extension-runtime.ts"));
    assert!(content.contains("./tool-schemas.ts"));
    assert!(content.contains("import.meta.url"));
    assert!(!content.contains("defineTool"));
    assert!(!content.contains("createHash"));
    assert!(!content.contains("canonicalJson"));

    fs::write(&generated_path, format!("{content}\n// drift\n")).expect("mutate generated");
    codegen_command()
        .current_dir(temp.path())
        .arg("--check")
        .assert()
        .code(1)
        .stderr(predicates::str::contains("child-extension.ts"));
}

#[test]
fn validation_tool_schema_embeds_named_finding_shape() {
    let temp = fixture();
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    let generated = fs::read_to_string(temp.path().join("src/generated/tool-schemas.ts"))
        .expect("read generated tool schemas");
    let schema_json = generated
        .split_once("export const VALIDATION_SUBMISSION_V2_TOOL_PARAMETERS = ")
        .expect("validation schema declaration")
        .1
        .split_once(" as TSchema;")
        .expect("validation schema terminator")
        .0;
    let schema: serde_json::Value =
        serde_json::from_str(schema_json).expect("validation schema JSON");
    let finding = &schema["properties"]["findings"]["items"];
    assert_eq!(finding["type"], "object");
    assert_eq!(finding["additionalProperties"], false);
    assert_eq!(finding["properties"]["finding_id"]["type"], "string");
    assert_eq!(finding["properties"]["kind"]["type"], "string");
    assert!(
        finding["required"]
            .as_array()
            .expect("finding required fields")
            .iter()
            .any(|field| field == "detail")
    );
    let digest = generated
        .split_once("export const VALIDATION_SUBMISSION_V2_TOOL_SCHEMA_DIGEST = \"")
        .expect("validation schema digest declaration")
        .1
        .split_once('"')
        .expect("validation schema digest terminator")
        .0;
    let kernel = fs::read_to_string(temp.path().join("kernel/src/generated/mod.rs"))
        .expect("read generated kernel contracts");
    let profile = kernel
        .split_once("\"validation-status.v2\"")
        .expect("validation terminal profile")
        .1
        .lines()
        .take(6)
        .collect::<Vec<_>>()
        .join("\n");
    assert!(
        profile.contains(digest),
        "Rust and TypeBox schema digests must match"
    );
}

#[test]
fn every_terminal_profile_uses_its_own_closedness_and_matches_rust() {
    let temp = fixture();
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    let generated = fs::read_to_string(temp.path().join("src/generated/tool-schemas.ts"))
        .expect("read generated tool schemas");
    let kernel = fs::read_to_string(temp.path().join("kernel/src/generated/mod.rs"))
        .expect("read generated kernel contracts");

    let schema = |name: &str| {
        let prefix = format!("export const {name} = ");
        let json = generated
            .split_once(&prefix)
            .unwrap_or_else(|| panic!("missing schema declaration {name}"))
            .1
            .split_once(" as TSchema;")
            .unwrap_or_else(|| panic!("missing schema terminator {name}"))
            .0;
        serde_json::from_str::<serde_json::Value>(json)
            .unwrap_or_else(|error| panic!("invalid schema JSON {name}: {error}"))
    };
    let open_work_map = schema("WORK_MAP_TOOL_PARAMETERS");
    let closed_work_map = schema("WORK_MAP_CLOSED_TOOL_PARAMETERS");
    assert_eq!(open_work_map["additionalProperties"], true);
    assert_eq!(closed_work_map["additionalProperties"], false);
    assert_eq!(
        closed_work_map["properties"]["units"]["items"]["additionalProperties"],
        false
    );

    let terminal_profiles = kernel
        .split_once("pub const TERMINAL_PROFILES")
        .expect("Rust terminal profile authority")
        .1;
    let submit_tools = generated
        .split_once("export const SUBMIT_TOOLS")
        .expect("TypeScript terminal profile authority")
        .1
        .split_once("] as const;")
        .expect("TypeScript terminal profile terminator")
        .0;
    let rows = submit_tools
        .lines()
        .filter(|line| line.trim_start().starts_with("{ profile_id: \""))
        .collect::<Vec<_>>();
    assert_eq!(rows.len(), 14, "all terminal profiles must be checked");
    for row in rows {
        let profile_id = row
            .split_once("profile_id: \"")
            .expect("profile field")
            .1
            .split_once('"')
            .expect("profile terminator")
            .0;
        let digest_name = row
            .split_once("schema_digest: ")
            .expect("digest field")
            .1
            .split_once(',')
            .expect("digest terminator")
            .0;
        let digest = generated
            .split_once(&format!("export const {digest_name} = \""))
            .unwrap_or_else(|| panic!("missing digest declaration {digest_name}"))
            .1
            .split_once('"')
            .expect("digest value terminator")
            .0;
        let rust_row = terminal_profiles
            .split_once(&format!("\"{profile_id}\""))
            .unwrap_or_else(|| panic!("missing Rust terminal profile {profile_id}"))
            .1
            .lines()
            .take(6)
            .collect::<Vec<_>>()
            .join("\n");
        assert!(
            rust_row.contains(digest),
            "Rust/TypeBox digest drift for terminal profile {profile_id}"
        );
        if profile_id == "recovery-work-map.v1" {
            assert!(row.contains("WORK_MAP_CLOSED_TOOL_SCHEMA_DIGEST"));
            assert!(row.contains("WORK_MAP_CLOSED_TOOL_PARAMETERS"));
        }
    }
}

#[test]
fn require_explicit_null_is_limited_to_required_nullable_fields() {
    let temp = fixture();
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    let generated = fs::read_to_string(temp.path().join("kernel/src/generated/mod.rs"))
        .expect("read generated Rust contracts");
    assert!(generated.contains(
        "#[serde(rename = \"provenance_manifest_destination\")]\n    #[serde(deserialize_with = \"deserialize_required_nullable\")]\n    pub provenance_manifest_destination: Nullable<Path>,"
    ));
    assert!(generated.contains(
        "#[serde(rename = \"linked_criterion\")]\n    #[serde(skip_serializing_if = \"Option::is_none\")]\n    pub linked_criterion: Option<Id>,"
    ));

    const EXPLICIT_NULL_FIELD: &str = "field \"provenance_manifest_destination\" type=\"path\" required=#true nullable=#true require_explicit_null=#true doc=\"Explicit null is the no-manifest form.\"";
    for (label, invalid) in [
        (
            "optional",
            "field \"provenance_manifest_destination\" type=\"path\" required=#false nullable=#true require_explicit_null=#true doc=\"Explicit null is the no-manifest form.\"",
        ),
        (
            "non-nullable",
            "field \"provenance_manifest_destination\" type=\"path\" required=#true require_explicit_null=#true doc=\"Explicit null is the no-manifest form.\"",
        ),
    ] {
        let temp = fixture();
        let contracts = temp.path().join("data/contracts.kdl");
        let source = fs::read_to_string(&contracts).expect("read contracts");
        fs::write(&contracts, source.replace(EXPLICIT_NULL_FIELD, invalid))
            .unwrap_or_else(|error| panic!("write {label} contract: {error}"));
        codegen_command()
            .current_dir(temp.path())
            .assert()
            .code(2)
            .stderr(predicate::str::contains(
                "requires required=#true nullable=#true",
            ));
    }
}

#[test]
fn min_bytes_emits_closed_blocked_tool_bounds_and_rejects_inversion() {
    let temp = fixture();
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    let generated = fs::read_to_string(temp.path().join("src/generated/tool-schemas.ts"))
        .expect("read generated tool schemas");
    let schema_json = generated
        .split_once("export const BLOCKED_REPORT_TOOL_PARAMETERS = ")
        .expect("blocked schema declaration")
        .1
        .split_once(" as TSchema;")
        .expect("blocked schema terminator")
        .0;
    let schema: serde_json::Value = serde_json::from_str(schema_json).expect("blocked schema JSON");
    assert_eq!(schema["additionalProperties"], serde_json::json!(false));
    assert_eq!(schema["properties"]["summary"]["minLength"], serde_json::json!(1));
    assert_eq!(schema["properties"]["summary"]["maxLength"], serde_json::json!(2000));
    assert_eq!(schema["properties"]["evidence"]["minItems"], serde_json::json!(1));

    let temp = fixture();
    let contracts = temp.path().join("data/contracts.kdl");
    let source = fs::read_to_string(&contracts).expect("read contracts");
    fs::write(
        &contracts,
        source.replace(
            "field \"summary\" type=\"string\" required=#true min_bytes=1 max_bytes=2000",
            "field \"summary\" type=\"string\" required=#true min_bytes=2001 max_bytes=2000",
        ),
    )
    .expect("write inverted min_bytes contract");
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .code(2)
        .stderr(predicate::str::contains("min_bytes greater than max_bytes"));
}

#[test]
fn unified_submit_contracts_emit_closed_frames_and_non_fifo_placeholder_metadata() {
    let temp = fixture();
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    let bridge = fs::read_to_string(temp.path().join("src/generated/child-control-bridge.ts"))
        .expect("read child-control bridge");
    assert!(bridge.starts_with("// @generated by codegen"));
    assert!(bridge.contains("CHILD_CONTROL_TERMINAL_PROFILE_COUNT = 14"));
    assert_eq!(bridge.matches("\"profile_id\":").count(), 15);
    assert!(bridge.contains("randomBytes(32)"));
    assert!(bridge.contains("new Map<string, PendingCall>()"));
    assert!(bridge.contains("PLACEHOLDER_TOKEN"));
    assert!(!bridge.contains("shift()"));

    let ts = fs::read_to_string(temp.path().join("src/generated/tool-schemas.ts"))
        .expect("read generated TypeBox schemas");
    assert_eq!(ts.matches("profile_id: \"").count(), 15);
    assert!(ts.contains("export const SUBMIT_TOOLS: readonly SubmitToolDescriptor[] = ["));
    assert!(ts.contains("export const UNIVERSAL_CHILD_TOOLS: readonly UniversalChildToolDescriptor[] = ["));
    assert!(ts.contains("autopilot_report_blocked"));
    assert!(ts.contains("NEVER use this tool unless you are genuinely stuck and no further work is possible. Accepted use immediately terminates the ENTIRE workstream and process, including every parallel line of work. Never use it for an ordinary retry — if your submit was rejected, fix the reported problem and submit again."));
    for digest in [
        "afea4f1dae10430432387da2f42545976e435850d19dd2026667d139b5950e37",
        "2ee4052fac867c671c6c972066aad7bfa8ab3fee07292de62c09c4bc0c4d41e2",
        "d1e73a08666c761604e71b81b58116ba057b0e3fe3103c3080b2b2a78a4b71dd",
        "f687b98000113e794d38368ebb55d903214d2cc25b3f4f5d3b0e578c6118e0b7",
        "b6b5f80aedcf8382f840f311bac4fdf1a6db5d83e0cf25eb46840e90043f8493",
        "4f341cc4aade90ac13c4584898f29b42d054d4ea4b5c126117841550e680ae75",
        "4b254caa4e21953efdc3102cb86c35c3238dfadc57b83fb083f5cbb49065857c",
        "60409306bbe13fcc510a6fb00450a50f71dbae44f4924dbfc5bd2eddf96810ed",
        "3ee75a8d7294cddd2f22261dedccc7a59f2403df9b0de761a6cdcd39ef986ab8",
        "0eb7655083ed7e8c707965ecb094134c1241f0d4355c271750fdde0300899674",
        "86052745eff30b746b44366bd1a9dc54aeee74aba63c1d6be80a187efc691545",
    ] {
        assert!(ts.contains(digest), "existing model-facing schema digest drift: {digest}");
    }

    let rust = fs::read_to_string(temp.path().join("kernel/src/generated/mod.rs"))
        .expect("read generated Rust contracts");
    let response = rust
        .split_once("pub enum ChildControlResponse")
        .expect("child-control response")
        .1
        .split_once("/// Create-once close archive manifest")
        .expect("next generated artifact")
        .0;
    assert!(rust.contains("#[serde(tag = \"outcome\", deny_unknown_fields)]\npub enum ChildControlResponse"));
    assert_eq!(response.matches("#[serde(rename = \"ACCEPT\")]").count(), 1);
    assert_eq!(response.matches("#[serde(rename = \"RETRY\")]").count(), 1);
    assert!(!response.contains("#[serde(rename = \"FATAL\")]"));
    assert!(rust.contains("pub struct SubmitDiagnostic"));
    assert!(rust.contains("pub struct SubmitReceipt"));
    assert!(rust.contains("pub struct BlockedReceipt"));
    assert!(rust.contains("pub struct BlockedLatch"));
    assert!(rust.contains("pub struct AgentRunSpecV5"));
    assert!(rust.contains("pub struct ValidationAssignmentV4"));
    let assignment_v4 = rust
        .split_once("pub struct ValidationAssignmentV4")
        .expect("fresh validation assignment")
        .1
        .split_once("/// Fact-only v3 Validator context")
        .expect("next artifact")
        .0;
    assert!(!assignment_v4.contains("max_value_attempts"));
}

#[test]
fn host_runtime_generation_and_mutations_fail_loudly() {
    let temp = fixture();
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    let generated = fs::read_to_string(temp.path().join("src/generated/host-runtime-tables.ts"))
        .expect("read host runtime tables");
    assert!(generated.contains("HOST_COMMANDS"));
    assert!(generated.contains("OPENAI_API_KEY"));
    assert!(generated.contains("spawn-wave"));
    assert!(generated.contains("id-json-object"));
    assert!(generated.contains("question_id"));
    fs::write(
        temp.path().join("src/generated/host-runtime-tables.ts"),
        format!("{generated}\n// drift\n"),
    )
    .expect("mutate generated");
    codegen_command()
        .current_dir(temp.path())
        .arg("--check")
        .assert()
        .code(1)
        .stderr(predicate::str::contains("host-runtime-tables.ts"));

    for (label, from, to, expected) in [
        (
            "missing env",
            "env_deny \"OPENAI_API_KEY\"\n",
            "",
            "missing env deny OPENAI_API_KEY",
        ),
        (
            "bad env",
            "env_deny \"OPENAI_API_KEY\"",
            "env_deny \"OpenAI_API_KEY\"",
            "malformed env name",
        ),
        (
            "bad max",
            "effect \"spawn-wave\" operator_level_default=\"info\" fail_closed=#false acknowledge=#true max_items=64",
            "effect \"spawn-wave\" operator_level_default=\"info\" fail_closed=#false acknowledge=#true max_items=63",
            "spawn-wave max drift",
        ),
        (
            "bad effect",
            "effect \"done\" operator_level_default=\"info\" fail_closed=#false acknowledge=#false",
            "effect \"mystery\" operator_level_default=\"info\" fail_closed=#false acknowledge=#false",
            "effect/seam drift",
        ),
        (
            "bad adapter",
            "adapter=\"id-json-object\"",
            "adapter=\"raw\"",
            "operator-answer adapter/payload drift",
        ),
        (
            "bad payload",
            "payload=\"HostToCoreOperatorAnswerPayload\"",
            "payload=\"HostToCoreCommandPayload\"",
            "command payload drift",
        ),
    ] {
        let temp = fixture();
        let path = temp.path().join("data/host-runtime.kdl");
        let content = fs::read_to_string(&path).expect("read host runtime");
        fs::write(&path, content.replace(from, to))
            .unwrap_or_else(|error| panic!("write {label}: {error}"));
        codegen_command()
            .current_dir(temp.path())
            .assert()
            .code(2)
            .stderr(predicate::str::contains(expected));
    }
    let temp = fixture();
    let path = temp.path().join("data/contracts.kdl");
    fs::write(
        &path,
        fs::read_to_string(&path).unwrap().replace(
            "field \"question_id\" type=\"id\" required=#true",
            "field \"question_id\" type=\"string\" required=#true",
        ),
    )
    .unwrap();
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .code(2)
        .stderr(predicate::str::contains(
            "operator-answer contract shape drift",
        ));
}

#[test]
fn v2_package_scope_codegen_mutation_regenerates_closed_schema_and_profiles() {
    let temp = fixture();
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    let contracts = temp.path().join("data/contracts.kdl");
    let source = fs::read_to_string(&contracts).expect("read contracts");
    fs::write(
        &contracts,
        source.replacen(
            "list \"package_scope_files\" item=\"path\" required=#true max_items=256",
            "list \"package_scope_files\" item=\"path\" required=#true max_items=255",
            1,
        ),
    )
    .expect("mutate V2 package scope authority");
    codegen_command()
        .current_dir(temp.path())
        .arg("--check")
        .assert()
        .code(1)
        .stderr(predicate::str::contains("generated output drift"));
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    codegen_command()
        .current_dir(temp.path())
        .arg("--check")
        .assert()
        .success();

    let rust = fs::read_to_string(temp.path().join("kernel/src/generated/mod.rs"))
        .expect("generated Rust");
    assert!(rust.contains("pub package_scope_files: Vec<Path>"));
    let ts = fs::read_to_string(temp.path().join("src/generated/tool-schemas.ts"))
        .expect("generated TypeBox schemas");
    let schema_json = ts
        .split_once("export const WORK_MAP_V2_CLOSED_TOOL_PARAMETERS = ")
        .expect("V2 closed schema")
        .1
        .split_once(" as TSchema;")
        .expect("V2 closed schema terminator")
        .0;
    let schema: serde_json::Value = serde_json::from_str(schema_json).expect("closed schema JSON");
    assert_eq!(schema["additionalProperties"], serde_json::json!(false));
    assert_eq!(
        schema["properties"]["units"]["items"]["properties"]["package_scope_files"]["maxItems"],
        serde_json::json!(255)
    );
    // These are the independently captured post-mutation contracts. Do not
    // derive an expected digest from the regenerated schema under test.
    const OPEN_DIGEST: &str = "013fd1091fc0992bf066dacbb48f093e65c666d50725d21611e1a9f5992d547b";
    const CLOSED_DIGEST: &str = "d8e8d6702062514a649d174c4e5dd17b4cae43c25aece52ce74f480e312ba807";
    assert!(ts.contains(&format!(
        "export const WORK_MAP_V2_TOOL_SCHEMA_DIGEST = \"{OPEN_DIGEST}\";"
    )));
    assert!(ts.contains(&format!(
        "export const WORK_MAP_V2_CLOSED_TOOL_SCHEMA_DIGEST = \"{CLOSED_DIGEST}\";"
    )));
    for (profile_id, name, digest) in [
        (
            "planning.work-map.v2:autopilot_submit_plan_cluster",
            "autopilot_submit_plan_cluster",
            OPEN_DIGEST,
        ),
        (
            "planning.work-map.v2:autopilot_submit_synthesis",
            "autopilot_submit_synthesis",
            OPEN_DIGEST,
        ),
        (
            "recovery-work-map.v2",
            "autopilot_emit_status",
            CLOSED_DIGEST,
        ),
    ] {
        let tuple = format!(
            "    (\n        \"{profile_id}\",\n        \"{name}\",\n        \"planning.work-map.v2\",\n        \"planning.work-map.v2\",\n        \"{digest}\",\n    ),"
        );
        assert!(
            rust.contains(&tuple),
            "missing exact V2 profile tuple: {tuple}"
        );
    }
}

#[test]
fn seam_mutations_fail_loudly() {
    let cases = [
        (
            "missing route",
            "route kind=\"done\" direction=\"core-to-host\" posture=\"supported\" payload=\"CoreToHostDonePayload\" adapter=\"none\" effect=\"done\"\n",
            "contract frame without seam route",
        ),
        (
            "duplicate route",
            "route kind=\"command\" direction=\"host-to-core\" posture=\"supported\" payload=\"HostToCoreCommandPayload\" adapter=\"command\" effect=\"none\"\nroute kind=\"command\" direction=\"host-to-core\" posture=\"supported\" payload=\"HostToCoreCommandPayload\" adapter=\"command\" effect=\"none\"\n",
            "duplicate seam route `command`",
        ),
        (
            "unknown property",
            "route kind=\"command\" direction=\"host-to-core\" posture=\"supported\" payload=\"HostToCoreCommandPayload\" adapter=\"command\" effect=\"none\" surprise=\"no\"\n",
            "unknown property",
        ),
        (
            "contract without route",
            "",
            "contract frame without seam route",
        ),
        (
            "direction drift",
            "route kind=\"command\" direction=\"core-to-host\" posture=\"supported\" payload=\"HostToCoreCommandPayload\" adapter=\"none\" effect=\"command\"\n",
            "has no contract frame",
        ),
        (
            "payload drift",
            "route kind=\"command\" direction=\"host-to-core\" posture=\"supported\" payload=\"CoreToHostDonePayload\" adapter=\"command\" effect=\"none\"\n",
            "direction/payload drift",
        ),
        (
            "bad posture",
            "route kind=\"command\" direction=\"host-to-core\" posture=\"maybe\" payload=\"HostToCoreCommandPayload\" adapter=\"command\" effect=\"none\"\n",
            "invalid posture",
        ),
    ];
    for (label, content, expected) in cases {
        let temp = fixture();
        fs::write(
            temp.path().join("data/seam.kdl"),
            format!("schema \"autopilot.seam.v1\"\nversion 1\n{content}"),
        )
        .unwrap_or_else(|error| panic!("write {label}: {error}"));
        codegen_command()
            .current_dir(temp.path())
            .assert()
            .code(2)
            .stderr(predicate::str::contains(expected));
    }
}
