use std::fs;
use std::path::Path;

use assert_cmd::Command;
use predicates::prelude::*;
use tempfile::TempDir;

fn fixture() -> TempDir {
    let temp = tempfile::tempdir().expect("tempdir");
    let data_dir = temp.path().join("data");
    fs::create_dir_all(&data_dir).expect("create data dir");
    for name in [
        "contracts.kdl",
        "seam.kdl",
        "host-runtime.kdl",
        "pi-rpc.kdl",
    ] {
        fs::copy(
            Path::new(env!("CARGO_MANIFEST_DIR")).join(format!("../data/{name}")),
            data_dir.join(name),
        )
        .expect("copy data");
    }
    temp
}

fn codegen_command() -> Command {
    Command::cargo_bin("codegen").expect("codegen binary")
}

#[test]
fn check_catches_a_hand_edit_and_recovers() {
    let temp = fixture();

    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    codegen_command()
        .current_dir(temp.path())
        .arg("--check")
        .assert()
        .success();

    let generated = temp.path().join("drivers/src/generated/tables.rs");
    let mut content = fs::read_to_string(&generated).expect("read generated file");
    content.push_str("// hand edit\n");
    fs::write(&generated, content).expect("mutate generated file");

    codegen_command()
        .current_dir(temp.path())
        .arg("--check")
        .assert()
        .code(1)
        .stderr(predicates::str::contains("first differing line"));

    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    codegen_command()
        .current_dir(temp.path())
        .arg("--check")
        .assert()
        .success();
}

#[test]
fn pi_rpc_generation_and_mutations_fail_loudly() {
    let temp = fixture();
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    let generated = temp.path().join("drivers/src/generated/pi_rpc.rs");
    let content = fs::read_to_string(&generated).expect("read pi rpc");
    assert!(content.contains("ENV_DENY"));
    assert!(content.contains("EventOrder"));
    fs::write(&generated, format!("{content}\n// drift\n")).expect("mutate generated");
    codegen_command()
        .current_dir(temp.path())
        .arg("--check")
        .assert()
        .code(1)
        .stderr(predicate::str::contains("pi_rpc.rs"));
    let temp = fixture();
    let path = temp.path().join("data/pi-rpc.kdl");
    let content = fs::read_to_string(&path).expect("read pi rpc kdl");
    fs::write(&path, content.replace("env_deny \"OPENAI_API_KEY\"\n", ""))
        .expect("mutate pi rpc kdl");
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .code(2)
        .stderr(predicate::str::contains("pi-rpc env_deny row drift"));
}

#[test]
fn unknown_kdl_node_is_rejected() {
    let temp = fixture();
    let contracts = temp.path().join("data/contracts.kdl");
    let mut content = fs::read_to_string(&contracts).expect("read contracts");
    content.push_str("\nbogus_node \"not allowed\"\n");
    fs::write(&contracts, content).expect("write bogus contracts");

    codegen_command()
        .current_dir(temp.path())
        .assert()
        .code(2)
        .stderr(
            predicates::str::contains("unknown top-level node `bogus_node`")
                .and(predicates::str::contains("line")),
        );
}

#[test]
fn frame_validation_output_is_generated_and_drift_checked() {
    let temp = fixture();
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    let generated = temp.path().join("src/generated/frame-validation.ts");
    let content = fs::read_to_string(&generated).expect("read frame validation");
    assert!(content.starts_with("// @generated by codegen"));
    assert!(content.contains("FRAME_VALIDATION_DESCRIPTORS"));
    assert!(content.contains("../frame-validation-runtime.ts"));
    assert!(content.contains("spawn-attested"));
    assert!(content.contains("list_constraints"));

    fs::write(&generated, format!("{content}\n// drift\n")).expect("mutate frame validation");
    codegen_command()
        .current_dir(temp.path())
        .arg("--check")
        .assert()
        .code(1)
        .stderr(predicates::str::contains("frame-validation.ts"));
}

#[test]
fn frame_validation_check_catches_contracts_and_seam_ts_drift() {
    let temp = fixture();
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    let contracts = temp.path().join("data/contracts.kdl");
    let content = fs::read_to_string(&contracts).expect("read contracts");
    fs::write(
        &contracts,
        content.replace(
            "field \"line\" type=\"string\" required=#true",
            "field \"line_extra\" type=\"string\" required=#true",
        ),
    )
    .expect("mutate contracts");
    codegen_command()
        .current_dir(temp.path())
        .arg("--check")
        .assert()
        .code(1)
        .stderr(predicates::str::contains("generated output drift"));

    let temp = fixture();
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    let seam = temp.path().join("data/seam.kdl");
    let content = fs::read_to_string(&seam).expect("read seam");
    fs::write(
        &seam,
        content.replace("effect=\"log\"", "effect=\"log-mutated\""),
    )
    .expect("mutate seam");
    codegen_command()
        .current_dir(temp.path())
        .arg("--check")
        .assert()
        .code(1)
        .stderr(predicates::str::contains("generated output drift"));
}

#[test]
fn child_extension_output_is_wrapper_and_drift_checked() {
    let temp = fixture();
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    let generated_path = temp.path().join("src/generated/child-extension.ts");
    let content = fs::read_to_string(&generated_path).expect("read child extension");
    assert!(content.starts_with("// @generated by codegen"));
    assert!(content.contains("../child-extension-runtime.ts"));
    assert!(content.contains("./tool-schemas.ts"));
    assert!(content.contains("import.meta.url"));
    assert!(!content.contains("defineTool"));
    assert!(!content.contains("createHash"));
    assert!(!content.contains("canonicalJson"));

    fs::write(&generated_path, format!("{content}\n// drift\n")).expect("mutate generated");
    codegen_command()
        .current_dir(temp.path())
        .arg("--check")
        .assert()
        .code(1)
        .stderr(predicates::str::contains("child-extension.ts"));
}

#[test]
fn host_runtime_generation_and_mutations_fail_loudly() {
    let temp = fixture();
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .success();
    let generated = fs::read_to_string(temp.path().join("src/generated/host-runtime-tables.ts"))
        .expect("read host runtime tables");
    assert!(generated.contains("HOST_COMMANDS"));
    assert!(generated.contains("OPENAI_API_KEY"));
    assert!(generated.contains("spawn-wave"));
    assert!(generated.contains("id-json-object"));
    assert!(generated.contains("question_id"));
    fs::write(
        temp.path().join("src/generated/host-runtime-tables.ts"),
        format!("{generated}\n// drift\n"),
    )
    .expect("mutate generated");
    codegen_command()
        .current_dir(temp.path())
        .arg("--check")
        .assert()
        .code(1)
        .stderr(predicate::str::contains("host-runtime-tables.ts"));

    for (label, from, to, expected) in [
        (
            "missing env",
            "env_deny \"OPENAI_API_KEY\"\n",
            "",
            "missing env deny OPENAI_API_KEY",
        ),
        (
            "bad env",
            "env_deny \"OPENAI_API_KEY\"",
            "env_deny \"OpenAI_API_KEY\"",
            "malformed env name",
        ),
        (
            "bad max",
            "effect \"spawn-wave\" operator_level_default=\"info\" fail_closed=#false acknowledge=#true max_items=64",
            "effect \"spawn-wave\" operator_level_default=\"info\" fail_closed=#false acknowledge=#true max_items=63",
            "spawn-wave max drift",
        ),
        (
            "bad effect",
            "effect \"done\" operator_level_default=\"info\" fail_closed=#false acknowledge=#false",
            "effect \"mystery\" operator_level_default=\"info\" fail_closed=#false acknowledge=#false",
            "effect/seam drift",
        ),
        (
            "bad adapter",
            "adapter=\"id-json-object\"",
            "adapter=\"raw\"",
            "operator-answer adapter/payload drift",
        ),
        (
            "bad payload",
            "payload=\"HostToCoreOperatorAnswerPayload\"",
            "payload=\"HostToCoreCommandPayload\"",
            "command payload drift",
        ),
    ] {
        let temp = fixture();
        let path = temp.path().join("data/host-runtime.kdl");
        let content = fs::read_to_string(&path).expect("read host runtime");
        fs::write(&path, content.replace(from, to))
            .unwrap_or_else(|error| panic!("write {label}: {error}"));
        codegen_command()
            .current_dir(temp.path())
            .assert()
            .code(2)
            .stderr(predicate::str::contains(expected));
    }
    let temp = fixture();
    let path = temp.path().join("data/contracts.kdl");
    fs::write(
        &path,
        fs::read_to_string(&path).unwrap().replace(
            "field \"question_id\" type=\"id\" required=#true",
            "field \"question_id\" type=\"string\" required=#true",
        ),
    )
    .unwrap();
    codegen_command()
        .current_dir(temp.path())
        .assert()
        .code(2)
        .stderr(predicate::str::contains(
            "operator-answer contract shape drift",
        ));
}

#[test]
fn seam_mutations_fail_loudly() {
    let cases = [
        (
            "missing route",
            "route kind=\"done\" direction=\"core-to-host\" posture=\"supported\" payload=\"CoreToHostDonePayload\" adapter=\"none\" effect=\"done\"\n",
            "contract frame without seam route",
        ),
        (
            "duplicate route",
            "route kind=\"command\" direction=\"host-to-core\" posture=\"supported\" payload=\"HostToCoreCommandPayload\" adapter=\"command\" effect=\"none\"\nroute kind=\"command\" direction=\"host-to-core\" posture=\"supported\" payload=\"HostToCoreCommandPayload\" adapter=\"command\" effect=\"none\"\n",
            "duplicate seam route `command`",
        ),
        (
            "unknown property",
            "route kind=\"command\" direction=\"host-to-core\" posture=\"supported\" payload=\"HostToCoreCommandPayload\" adapter=\"command\" effect=\"none\" surprise=\"no\"\n",
            "unknown property",
        ),
        (
            "contract without route",
            "",
            "contract frame without seam route",
        ),
        (
            "direction drift",
            "route kind=\"command\" direction=\"core-to-host\" posture=\"supported\" payload=\"HostToCoreCommandPayload\" adapter=\"none\" effect=\"command\"\n",
            "has no contract frame",
        ),
        (
            "payload drift",
            "route kind=\"command\" direction=\"host-to-core\" posture=\"supported\" payload=\"CoreToHostDonePayload\" adapter=\"command\" effect=\"none\"\n",
            "direction/payload drift",
        ),
        (
            "bad posture",
            "route kind=\"command\" direction=\"host-to-core\" posture=\"maybe\" payload=\"HostToCoreCommandPayload\" adapter=\"command\" effect=\"none\"\n",
            "invalid posture",
        ),
    ];
    for (label, content, expected) in cases {
        let temp = fixture();
        fs::write(
            temp.path().join("data/seam.kdl"),
            format!("schema \"autopilot.seam.v1\"\nversion 1\n{content}"),
        )
        .unwrap_or_else(|error| panic!("write {label}: {error}"));
        codegen_command()
            .current_dir(temp.path())
            .assert()
            .code(2)
            .stderr(predicate::str::contains(expected));
    }
}
