use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use kdl::{KdlDocument, KdlEntry, KdlNode, KdlValue};
use serde_json::{Map as JsonMap, Value as JsonValue, json};
use sha2::{Digest as ShaDigest, Sha256};

const GENERATED_MARKER: &str = "@generated by codegen";

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("{error}");
            ExitCode::from(error.exit_code())
        }
    }
}

fn run() -> Result<(), CodegenError> {
    let mut check = false;
    for arg in std::env::args().skip(1) {
        if arg == "--check" {
            check = true;
        } else {
            return Err(CodegenError::Usage(format!("unknown argument: {arg}")));
        }
    }

    let source_path = Path::new("data/contracts.kdl");
    let source = std::fs::read_to_string(source_path).map_err(|error| {
        CodegenError::Input(format!("failed to read data/contracts.kdl: {error}"))
    })?;
    let contracts = Contracts::parse(&source)?;
    let outputs = emit_all(&contracts)?;

    if check {
        check_outputs(&outputs)
    } else {
        write_outputs(&outputs)
    }
}

#[derive(Debug)]
enum CodegenError {
    Usage(String),
    Input(String),
    Io(String),
    Drift(String),
}

impl CodegenError {
    fn exit_code(&self) -> u8 {
        match self {
            Self::Usage(_) => 64,
            Self::Input(_) => 2,
            Self::Io(_) | Self::Drift(_) => 1,
        }
    }
}

impl std::fmt::Display for CodegenError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Usage(message)
            | Self::Input(message)
            | Self::Io(message)
            | Self::Drift(message) => {
                write!(formatter, "{message}")
            }
        }
    }
}

#[derive(Debug, Clone)]
struct Contracts {
    schema: String,
    version: u64,
    types: BTreeSet<String>,
    constants: BTreeMap<String, String>,
    artifacts: Vec<Artifact>,
    enums: Vec<EnumDef>,
    frames: Vec<Frame>,
}

#[derive(Debug, Clone)]
struct Artifact {
    name: String,
    schema: String,
    model_produced: bool,
    doc: String,
    admits: Option<String>,
    items: Vec<Item>,
}

#[derive(Debug, Clone)]
struct Frame {
    direction: String,
    kind: String,
    doc: String,
    items: Vec<Item>,
}

#[derive(Debug, Clone)]
struct EnumDef {
    name: String,
    values: Vec<String>,
    doc: Option<String>,
}

#[derive(Debug, Clone)]
enum Item {
    Field(Field),
    List(List),
    Group(Group),
    Record(Record),
}

#[derive(Debug, Clone)]
struct Field {
    name: String,
    type_id: String,
    required: bool,
    nullable: bool,
    doc: Option<String>,
}

#[derive(Debug, Clone)]
struct List {
    name: String,
    item_type: String,
    required: bool,
    nullable: bool,
    doc: Option<String>,
}

#[derive(Debug, Clone)]
struct Group {
    name: String,
    required: bool,
    items: Vec<Item>,
}

#[derive(Debug, Clone)]
struct Record {
    name: String,
    items: Vec<Item>,
}

impl Contracts {
    fn parse(source: &str) -> Result<Self, CodegenError> {
        let doc = source.parse::<KdlDocument>().map_err(|error| {
            CodegenError::Input(format!("failed to parse data/contracts.kdl: {error}"))
        })?;
        let mut schema = None;
        let mut version = None;
        let mut types = BTreeSet::new();
        let mut constants = BTreeMap::new();
        let mut artifacts = Vec::new();
        let mut enums = Vec::new();
        let mut frames = Vec::new();

        for node in doc.nodes() {
            match name(node) {
                "schema" => {
                    ensure_entries(node, 1, &[], source)?;
                    schema = Some(arg_string(node, 0, source)?.to_owned());
                    ensure_no_children(node, source)?;
                }
                "version" => {
                    ensure_entries(node, 1, &[], source)?;
                    version = Some(arg_u64(node, 0, source)?);
                    ensure_no_children(node, source)?;
                }
                "doc" => {
                    ensure_entries(node, 1, &[], source)?;
                    ensure_no_children(node, source)?;
                }
                "type" => {
                    ensure_entries(node, 1, &["doc"], source)?;
                    types.insert(arg_string(node, 0, source)?.to_owned());
                    prop_string_optional(node, "doc", source)?;
                    ensure_no_children(node, source)?;
                }
                "artifact" => artifacts.push(parse_artifact(node, source)?),
                "enum" => enums.push(parse_enum(node, source)?),
                "frame" => frames.push(parse_frame(node, source)?),
                "constant" => {
                    ensure_entries(node, 1, &["value", "doc"], source)?;
                    let key = arg_string(node, 0, source)?.to_owned();
                    let value = prop_string(node, "value", source)?.to_owned();
                    prop_string_optional(node, "doc", source)?;
                    ensure_no_children(node, source)?;
                    if constants.insert(key.clone(), value).is_some() {
                        return Err(CodegenError::Input(format!(
                            "duplicate constant `{key}` at line {}",
                            line_of(node, source)
                        )));
                    }
                }
                "artifact_category" => {
                    ensure_entries(node, 1, &["path", "doc"], source)?;
                    arg_string(node, 0, source)?;
                    prop_string(node, "path", source)?;
                    prop_string_optional(node, "doc", source)?;
                    ensure_no_children(node, source)?;
                }
                "resource_gate" => {
                    ensure_entries(
                        node,
                        1,
                        &["default", "counts", "doc", "value", "threshold", "effect"],
                        source,
                    )?;
                    arg_string(node, 0, source)?;
                    for key in ["default", "counts", "doc", "value", "threshold", "effect"] {
                        prop_string_optional(node, key, source)?;
                    }
                    ensure_no_children(node, source)?;
                }
                "scheduler_order" => {
                    ensure_entries(node, 1, &["key", "direction"], source)?;
                    arg_u64(node, 0, source)?;
                    prop_string(node, "key", source)?;
                    prop_string(node, "direction", source)?;
                    ensure_no_children(node, source)?;
                }
                other => {
                    return Err(CodegenError::Input(format!(
                        "unknown top-level node `{other}` at line {}",
                        line_of(node, source)
                    )));
                }
            }
        }

        let schema = schema.ok_or_else(|| {
            CodegenError::Input("missing required top-level schema node".to_owned())
        })?;
        let version = version.ok_or_else(|| {
            CodegenError::Input("missing required top-level version node".to_owned())
        })?;
        let contracts = Self {
            schema,
            version,
            types,
            constants,
            artifacts,
            enums,
            frames,
        };
        contracts.validate_types()?;
        Ok(contracts)
    }

    fn validate_types(&self) -> Result<(), CodegenError> {
        let mut known = builtin_scalar_types();
        known.extend(self.types.iter().cloned());
        known.extend(self.enums.iter().map(|entry| entry.name.clone()));
        known.extend(self.artifacts.iter().map(|entry| entry.name.clone()));
        for artifact in &self.artifacts {
            collect_record_names(&artifact.items, &mut known);
        }

        for artifact in &self.artifacts {
            validate_item_types(
                &artifact.items,
                &known,
                &format!("artifact `{}`", artifact.name),
            )?;
        }
        for frame in &self.frames {
            validate_item_types(&frame.items, &known, &format!("frame `{}`", frame.kind))?;
        }
        Ok(())
    }
}

fn builtin_scalar_types() -> BTreeSet<String> {
    [
        "authority-class",
        "base32",
        "bool",
        "contract-id",
        "control_observation",
        "delivery-boundary",
        "delivery-terminal-status",
        "duration",
        "event-kind",
        "guard-decision",
        "mode-id",
        "object",
        "path",
        "permission",
        "redaction-state",
        "schema-id",
        "session-action",
        "string",
        "supersession-state",
        "test-id",
        "thinking-level",
        "tool-name",
        "trigger-kind",
        "u32",
        "u64",
        "u8",
        "ui-kind",
        "uri",
        "validation-scope",
    ]
    .into_iter()
    .map(str::to_owned)
    .collect()
}

fn collect_record_names(items: &[Item], known: &mut BTreeSet<String>) {
    for item in items {
        match item {
            Item::Record(record) => {
                known.insert(record.name.clone());
                collect_record_names(&record.items, known);
            }
            Item::Group(group) => collect_record_names(&group.items, known),
            Item::Field(_) | Item::List(_) => {}
        }
    }
}

fn validate_item_types(
    items: &[Item],
    known: &BTreeSet<String>,
    owner: &str,
) -> Result<(), CodegenError> {
    for item in items {
        match item {
            Item::Field(field) => {
                if !known.contains(&field.type_id) {
                    return Err(CodegenError::Input(format!(
                        "unknown type `{}` for field `{}` in {owner}",
                        field.type_id, field.name
                    )));
                }
            }
            Item::List(list) => {
                if !known.contains(&list.item_type) {
                    return Err(CodegenError::Input(format!(
                        "unknown list item type `{}` for list `{}` in {owner}",
                        list.item_type, list.name
                    )));
                }
            }
            Item::Group(group) => validate_item_types(&group.items, known, owner)?,
            Item::Record(record) => validate_item_types(&record.items, known, owner)?,
        }
    }
    Ok(())
}

fn parse_artifact(node: &KdlNode, source: &str) -> Result<Artifact, CodegenError> {
    ensure_entries(node, 1, &["schema", "producer", "model_produced"], source)?;
    let artifact_name = arg_string(node, 0, source)?.to_owned();
    let schema = prop_string(node, "schema", source)?.to_owned();
    prop_string(node, "producer", source)?;
    let model_produced = prop_bool(node, "model_produced", source)?;
    let children = children(node, source)?;
    let mut doc = None;
    let mut admits = None;
    let mut items = Vec::new();
    for child in children.nodes() {
        match name(child) {
            "doc" => {
                ensure_entries(child, 1, &[], source)?;
                doc = Some(arg_string(child, 0, source)?.to_owned());
                ensure_no_children(child, source)?;
            }
            "admits" => {
                ensure_entries(child, 1, &[], source)?;
                let text = arg_string(child, 0, source)?.to_owned();
                if text.is_empty() {
                    return Err(CodegenError::Input(format!(
                        "empty admits text in artifact `{artifact_name}` at line {}",
                        line_of(child, source)
                    )));
                }
                admits = Some(text);
                ensure_no_children(child, source)?;
            }
            "field" => items.push(Item::Field(parse_field(child, source)?)),
            "list" => items.push(Item::List(parse_list(child, source)?)),
            "group" => items.push(Item::Group(parse_group(child, source)?)),
            "record" => items.push(Item::Record(parse_record(child, source)?)),
            "pattern" => parse_pattern(child, source)?,
            "constant" => parse_constant_child(child, source)?,
            other => {
                return Err(CodegenError::Input(format!(
                    "unknown child node `{other}` in artifact `{artifact_name}` at line {}",
                    line_of(child, source)
                )));
            }
        }
    }
    let doc = doc
        .ok_or_else(|| CodegenError::Input(format!("missing doc in artifact `{artifact_name}`")))?;
    if model_produced && admits.is_none() {
        return Err(CodegenError::Input(format!(
            "model-produced artifact `{artifact_name}` is missing non-empty admits text"
        )));
    }
    Ok(Artifact {
        name: artifact_name,
        schema,
        model_produced,
        doc,
        admits,
        items,
    })
}

fn parse_frame(node: &KdlNode, source: &str) -> Result<Frame, CodegenError> {
    ensure_entries(node, 0, &["direction", "kind"], source)?;
    let direction = prop_string(node, "direction", source)?.to_owned();
    if direction != "host-to-core" && direction != "core-to-host" {
        return Err(CodegenError::Input(format!(
            "unknown frame direction `{direction}` at line {}",
            line_of(node, source)
        )));
    }
    let kind = prop_string(node, "kind", source)?.to_owned();
    let children = children(node, source)?;
    let mut doc = None;
    let mut items = Vec::new();
    for child in children.nodes() {
        match name(child) {
            "doc" => {
                ensure_entries(child, 1, &[], source)?;
                doc = Some(arg_string(child, 0, source)?.to_owned());
                ensure_no_children(child, source)?;
            }
            "field" => items.push(Item::Field(parse_field(child, source)?)),
            "list" => items.push(Item::List(parse_list(child, source)?)),
            "group" => items.push(Item::Group(parse_group(child, source)?)),
            "record" => items.push(Item::Record(parse_record(child, source)?)),
            other => {
                return Err(CodegenError::Input(format!(
                    "unknown child node `{other}` in frame `{kind}` at line {}",
                    line_of(child, source)
                )));
            }
        }
    }
    let doc = doc.ok_or_else(|| CodegenError::Input(format!("missing doc in frame `{kind}`")))?;
    Ok(Frame {
        direction,
        kind,
        doc,
        items,
    })
}

fn parse_field(node: &KdlNode, source: &str) -> Result<Field, CodegenError> {
    ensure_entries(
        node,
        1,
        &["type", "required", "nullable", "doc", "constant"],
        source,
    )?;
    let name = arg_string(node, 0, source)?.to_owned();
    let type_id = prop_string(node, "type", source)?.to_owned();
    let required = prop_bool(node, "required", source)?;
    let nullable = prop_bool_optional(node, "nullable", source)?.unwrap_or(false);
    let doc = prop_string_optional(node, "doc", source)?.map(str::to_owned);
    let constant = prop_string_optional(node, "constant", source)?.map(str::to_owned);
    if let Some(value) = &constant {
        validate_constant(&name, &type_id, value, node, source)?;
    }
    ensure_no_children(node, source)?;
    Ok(Field {
        name,
        type_id,
        required,
        nullable,
        doc,
    })
}

fn validate_constant(
    field_name: &str,
    type_id: &str,
    value: &str,
    node: &KdlNode,
    source: &str,
) -> Result<(), CodegenError> {
    match type_id {
        "u8" | "u32" | "u64" => value.parse::<u64>().map(|_| ()).map_err(|error| {
            CodegenError::Input(format!(
                "constant `{value}` for numeric field `{field_name}` at line {} is invalid: {error}",
                line_of(node, source)
            ))
        }),
        "bool" => value.parse::<bool>().map(|_| ()).map_err(|error| {
            CodegenError::Input(format!(
                "constant `{value}` for bool field `{field_name}` at line {} is invalid: {error}",
                line_of(node, source)
            ))
        }),
        _ => Ok(()),
    }
}

fn parse_list(node: &KdlNode, source: &str) -> Result<List, CodegenError> {
    ensure_entries(node, 1, &["item", "required", "nullable", "doc"], source)?;
    let name = arg_string(node, 0, source)?.to_owned();
    let item_type = prop_string(node, "item", source)?.to_owned();
    let required = prop_bool(node, "required", source)?;
    let nullable = prop_bool_optional(node, "nullable", source)?.unwrap_or(false);
    let doc = prop_string_optional(node, "doc", source)?.map(str::to_owned);
    ensure_no_children(node, source)?;
    Ok(List {
        name,
        item_type,
        required,
        nullable,
        doc,
    })
}

fn parse_group(node: &KdlNode, source: &str) -> Result<Group, CodegenError> {
    ensure_entries(node, 1, &["required"], source)?;
    let name = arg_string(node, 0, source)?.to_owned();
    let required = prop_bool(node, "required", source)?;
    let children = children(node, source)?;
    let items = parse_shape_children(children.nodes(), &format!("group `{name}`"), source)?;
    Ok(Group {
        name,
        required,
        items,
    })
}

fn parse_record(node: &KdlNode, source: &str) -> Result<Record, CodegenError> {
    ensure_entries(node, 1, &[], source)?;
    let name = arg_string(node, 0, source)?.to_owned();
    let children = children(node, source)?;
    let items = parse_shape_children(children.nodes(), &format!("record `{name}`"), source)?;
    Ok(Record { name, items })
}

fn parse_shape_children(
    nodes: &[KdlNode],
    owner: &str,
    source: &str,
) -> Result<Vec<Item>, CodegenError> {
    let mut items = Vec::new();
    for child in nodes {
        match name(child) {
            "field" => items.push(Item::Field(parse_field(child, source)?)),
            "list" => items.push(Item::List(parse_list(child, source)?)),
            "group" => items.push(Item::Group(parse_group(child, source)?)),
            "record" => items.push(Item::Record(parse_record(child, source)?)),
            other => {
                return Err(CodegenError::Input(format!(
                    "unknown child node `{other}` in {owner} at line {}",
                    line_of(child, source)
                )));
            }
        }
    }
    Ok(items)
}

fn parse_enum(node: &KdlNode, source: &str) -> Result<EnumDef, CodegenError> {
    ensure_entries(node, 1, &[], source)?;
    let enum_name = arg_string(node, 0, source)?.to_owned();
    let children = children(node, source)?;
    let mut doc = None;
    let mut values = Vec::new();
    for child in children.nodes() {
        match name(child) {
            "doc" => {
                ensure_entries(child, 1, &[], source)?;
                doc = Some(arg_string(child, 0, source)?.to_owned());
                ensure_no_children(child, source)?;
            }
            "value" => {
                ensure_entries(child, 1, &[], source)?;
                values.push(arg_string(child, 0, source)?.to_owned());
                ensure_no_children(child, source)?;
            }
            other => {
                return Err(CodegenError::Input(format!(
                    "unknown child node `{other}` in enum `{enum_name}` at line {}",
                    line_of(child, source)
                )));
            }
        }
    }
    if values.is_empty() {
        return Err(CodegenError::Input(format!(
            "enum `{enum_name}` has no values"
        )));
    }
    Ok(EnumDef {
        name: enum_name,
        values,
        doc,
    })
}

fn parse_pattern(node: &KdlNode, source: &str) -> Result<(), CodegenError> {
    ensure_entries(node, 1, &["anchor_form", "value", "doc"], source)?;
    arg_string(node, 0, source)?;
    prop_string(node, "anchor_form", source)?;
    prop_string(node, "value", source)?;
    prop_string_optional(node, "doc", source)?;
    ensure_no_children(node, source)
}

fn parse_constant_child(node: &KdlNode, source: &str) -> Result<(), CodegenError> {
    ensure_entries(node, 1, &["value", "doc"], source)?;
    arg_string(node, 0, source)?;
    prop_string(node, "value", source)?;
    prop_string_optional(node, "doc", source)?;
    ensure_no_children(node, source)
}

fn ensure_entries(
    node: &KdlNode,
    positional: usize,
    allowed_props: &[&str],
    source: &str,
) -> Result<(), CodegenError> {
    let mut positional_seen = 0usize;
    let allowed: BTreeSet<&str> = allowed_props.iter().copied().collect();
    let mut props_seen = BTreeSet::new();
    for entry in node.entries() {
        if entry.ty().is_some() {
            return Err(CodegenError::Input(format!(
                "typed KDL entry on node `{}` is unsupported at line {}",
                name(node),
                line_of_entry(entry, source)
            )));
        }
        if let Some(entry_name) = entry.name() {
            let key = entry_name.value();
            if !allowed.contains(key) {
                return Err(CodegenError::Input(format!(
                    "unknown property `{key}` on node `{}` at line {}",
                    name(node),
                    line_of_entry(entry, source)
                )));
            }
            if !props_seen.insert(key.to_owned()) {
                return Err(CodegenError::Input(format!(
                    "duplicate property `{key}` on node `{}` at line {}",
                    name(node),
                    line_of_entry(entry, source)
                )));
            }
        } else {
            positional_seen += 1;
            if positional_seen > positional {
                return Err(CodegenError::Input(format!(
                    "unexpected argument {} on node `{}` at line {}",
                    positional_seen,
                    name(node),
                    line_of_entry(entry, source)
                )));
            }
        }
    }
    if positional_seen != positional {
        return Err(CodegenError::Input(format!(
            "node `{}` at line {} requires {positional} argument(s), found {positional_seen}",
            name(node),
            line_of(node, source)
        )));
    }
    Ok(())
}

fn ensure_no_children(node: &KdlNode, source: &str) -> Result<(), CodegenError> {
    if node.children().is_some() {
        return Err(CodegenError::Input(format!(
            "node `{}` at line {} must not have children",
            name(node),
            line_of(node, source)
        )));
    }
    Ok(())
}

fn children<'a>(node: &'a KdlNode, source: &str) -> Result<&'a KdlDocument, CodegenError> {
    node.children().ok_or_else(|| {
        CodegenError::Input(format!(
            "node `{}` at line {} requires children",
            name(node),
            line_of(node, source)
        ))
    })
}

fn name(node: &KdlNode) -> &str {
    node.name().value()
}

fn arg_value<'a>(
    node: &'a KdlNode,
    index: usize,
    source: &str,
) -> Result<&'a KdlValue, CodegenError> {
    node.entries()
        .iter()
        .filter(|entry| entry.name().is_none())
        .nth(index)
        .map(KdlEntry::value)
        .ok_or_else(|| {
            CodegenError::Input(format!(
                "missing argument {index} on node `{}` at line {}",
                name(node),
                line_of(node, source)
            ))
        })
}

fn arg_string<'a>(node: &'a KdlNode, index: usize, source: &str) -> Result<&'a str, CodegenError> {
    arg_value(node, index, source)?.as_string().ok_or_else(|| {
        CodegenError::Input(format!(
            "argument {index} on node `{}` at line {} must be a string",
            name(node),
            line_of(node, source)
        ))
    })
}

fn arg_u64(node: &KdlNode, index: usize, source: &str) -> Result<u64, CodegenError> {
    let integer = arg_value(node, index, source)?
        .as_integer()
        .ok_or_else(|| {
            CodegenError::Input(format!(
                "argument {index} on node `{}` at line {} must be an integer",
                name(node),
                line_of(node, source)
            ))
        })?;
    u64::try_from(integer).map_err(|_| {
        CodegenError::Input(format!(
            "argument {index} on node `{}` at line {} must be a non-negative integer",
            name(node),
            line_of(node, source)
        ))
    })
}

fn prop_value<'a>(
    node: &'a KdlNode,
    key: &str,
    source: &str,
) -> Result<&'a KdlValue, CodegenError> {
    node.entry(key).map(KdlEntry::value).ok_or_else(|| {
        CodegenError::Input(format!(
            "missing required property `{key}` on node `{}` at line {}",
            name(node),
            line_of(node, source)
        ))
    })
}

fn prop_string<'a>(node: &'a KdlNode, key: &str, source: &str) -> Result<&'a str, CodegenError> {
    prop_value(node, key, source)?.as_string().ok_or_else(|| {
        CodegenError::Input(format!(
            "property `{key}` on node `{}` at line {} must be a string",
            name(node),
            line_of(node, source)
        ))
    })
}

fn prop_string_optional<'a>(
    node: &'a KdlNode,
    key: &str,
    source: &str,
) -> Result<Option<&'a str>, CodegenError> {
    match node.entry(key) {
        Some(entry) => entry.value().as_string().map(Some).ok_or_else(|| {
            CodegenError::Input(format!(
                "property `{key}` on node `{}` at line {} must be a string",
                name(node),
                line_of_entry(entry, source)
            ))
        }),
        None => Ok(None),
    }
}

fn prop_bool(node: &KdlNode, key: &str, source: &str) -> Result<bool, CodegenError> {
    prop_value(node, key, source)?.as_bool().ok_or_else(|| {
        CodegenError::Input(format!(
            "property `{key}` on node `{}` at line {} must be a boolean",
            name(node),
            line_of(node, source)
        ))
    })
}

fn prop_bool_optional(
    node: &KdlNode,
    key: &str,
    source: &str,
) -> Result<Option<bool>, CodegenError> {
    match node.entry(key) {
        Some(entry) => entry.value().as_bool().map(Some).ok_or_else(|| {
            CodegenError::Input(format!(
                "property `{key}` on node `{}` at line {} must be a boolean",
                name(node),
                line_of_entry(entry, source)
            ))
        }),
        None => Ok(None),
    }
}

fn line_of(node: &KdlNode, source: &str) -> usize {
    line_for_offset(source, node.span().offset())
}

fn line_of_entry(entry: &KdlEntry, source: &str) -> usize {
    line_for_offset(source, entry.span().offset())
}

fn line_for_offset(source: &str, offset: usize) -> usize {
    source[..offset.min(source.len())]
        .bytes()
        .filter(|byte| *byte == b'\n')
        .count()
        + 1
}

#[derive(Debug)]
struct OutputFile {
    path: PathBuf,
    content: String,
}

fn emit_all(contracts: &Contracts) -> Result<Vec<OutputFile>, CodegenError> {
    let (rust, typescript) = emit_rust_typescript(contracts)?;
    let tool_schemas = emit_tool_schemas(contracts)?;
    let mut outputs = vec![
        OutputFile {
            path: PathBuf::from("kernel/src/generated/mod.rs"),
            content: rust,
        },
        OutputFile {
            path: PathBuf::from("host/src/generated/index.ts"),
            content: typescript.clone(),
        },
        OutputFile {
            path: PathBuf::from("src/generated/index.ts"),
            content: typescript,
        },
        OutputFile {
            path: PathBuf::from("src/generated/tool-schemas.ts"),
            content: tool_schemas,
        },
    ];

    let mut artifacts = contracts.artifacts.clone();
    artifacts.sort_by(|left, right| left.name.cmp(&right.name));
    for artifact in artifacts {
        if let Some(admits) = &artifact.admits {
            outputs.push(OutputFile {
                path: PathBuf::from(format!("generated/prompts/{}.md", artifact.name)),
                content: emit_prompt(&artifact.name, admits),
            });
        }
    }
    outputs.sort_by(|left, right| left.path.cmp(&right.path));
    Ok(outputs)
}

fn emit_rust_typescript(contracts: &Contracts) -> Result<(String, String), CodegenError> {
    let mut rust = String::new();
    rust.push_str("// ");
    rust.push_str(GENERATED_MARKER);
    rust.push_str("\n\n");
    rust.push_str("use serde::{Deserialize, Serialize};\n\n");
    rust.push_str("#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]\n");
    rust.push_str("#[serde(transparent)]\n");
    rust.push_str("pub struct Nullable<T>(pub Option<T>);\n\n");

    let mut typescript = String::new();
    typescript.push_str("// ");
    typescript.push_str(GENERATED_MARKER);
    typescript.push_str("\n\n");
    typescript.push_str("export type JsonObject = Record<string, unknown>;\n");
    typescript.push_str(&format!(
        "export const GUARD_TIMEOUT_DEFAULT_MS = {};\n\n",
        duration_ms(required_constant(contracts, "guard_timeout_default")?)?
    ));

    let mut scalar_types: Vec<String> = contracts
        .types
        .iter()
        .filter(|name| should_emit_newtype(name))
        .cloned()
        .collect();
    scalar_types.extend(
        builtin_scalar_types()
            .into_iter()
            .filter(|name| should_emit_newtype(name) && !contracts.types.contains(name)),
    );
    scalar_types.sort();
    scalar_types.dedup();
    for scalar in &scalar_types {
        let ty = rust_type_name(scalar);
        rust.push_str("#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]\n");
        rust.push_str("#[serde(transparent)]\n");
        rust.push_str(&format!("pub struct {ty}(pub String);\n\n"));
        typescript.push_str(&format!("export type {ty} = string;\n"));
    }
    typescript.push('\n');

    let mut enums = contracts.enums.clone();
    enums.sort_by(|left, right| left.name.cmp(&right.name));
    for enum_def in &enums {
        let ty = rust_type_name(&enum_def.name);
        if let Some(doc) = &enum_def.doc {
            rust.push_str(&rust_doc(doc));
        }
        rust.push_str("#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]\n");
        rust.push_str(&format!("pub enum {ty} {{\n"));
        let mut values = enum_def.values.clone();
        values.sort();
        for value in values {
            rust.push_str(&format!(
                "    #[serde(rename = \"{}\")]\n    {},\n",
                escape_rust_string(&value),
                rust_variant_name(&value)
            ));
        }
        rust.push_str("}\n\n");
        let values = enum_def
            .values
            .iter()
            .map(|value| format!("\"{}\"", escape_ts_string(value)))
            .collect::<Vec<_>>()
            .join(" | ");
        typescript.push_str(&format!("export type {ty} = {values};\n"));
    }
    typescript.push('\n');

    let mut artifacts = contracts.artifacts.clone();
    artifacts.sort_by(|left, right| left.name.cmp(&right.name));
    for artifact in &artifacts {
        let type_name = rust_type_name(&artifact.name);
        emit_shape_tree(
            &mut rust,
            &mut typescript,
            &type_name,
            &artifact.doc,
            &artifact.items,
            artifact.model_produced,
        );
    }

    let mut frame_names = Vec::new();
    let mut frames = contracts.frames.clone();
    frames.sort_by(|left, right| {
        (left.direction.as_str(), left.kind.as_str())
            .cmp(&(right.direction.as_str(), right.kind.as_str()))
    });
    for frame in &frames {
        let name = frame_type_name(frame);
        frame_names.push((frame.direction.clone(), frame.kind.clone(), name.clone()));
        emit_shape_tree(
            &mut rust,
            &mut typescript,
            &name,
            &frame.doc,
            &frame.items,
            false,
        );
    }

    rust.push_str("pub const CONTRACT_SCHEMA: &str = ");
    rust.push_str(&format!("\"{}\";\n", escape_rust_string(&contracts.schema)));
    rust.push_str("pub const CONTRACT_VERSION: u64 = ");
    rust.push_str(&format!("{};\n\n", contracts.version));
    let mut admits = BTreeMap::new();
    for artifact in &contracts.artifacts {
        if let Some(text) = &artifact.admits {
            admits.insert(artifact.name.clone(), text.clone());
        }
    }
    for (name, text) in admits {
        rust.push_str(&format!(
            "pub const {}_ADMITS: &str = \"{}\";\n",
            screaming_name(&name),
            escape_rust_string(&text)
        ));
    }

    let host_to_core = frame_names
        .iter()
        .filter(|(direction, _, _)| direction == "host-to-core")
        .map(|(_, kind, name)| {
            format!(
                "{{ v: 1; id: number; kind: \"{}\"; payload: {} }}",
                escape_ts_string(kind),
                name
            )
        })
        .collect::<Vec<_>>()
        .join(" | ");
    let core_to_host = frame_names
        .iter()
        .filter(|(direction, _, _)| direction == "core-to-host")
        .map(|(_, kind, name)| {
            format!(
                "{{ v: 1; id: number; kind: \"{}\"; payload: {} }}",
                escape_ts_string(kind),
                name
            )
        })
        .collect::<Vec<_>>()
        .join(" | ");
    typescript.push_str(&format!(
        "export type HostToCoreFrame = {};\n",
        host_to_core
    ));
    typescript.push_str(&format!(
        "export type CoreToHostFrame = {};\n",
        core_to_host
    ));

    Ok((rust, typescript))
}

fn emit_tool_schemas(contracts: &Contracts) -> Result<String, CodegenError> {
    let mut out = String::new();
    out.push_str("// ");
    out.push_str(GENERATED_MARKER);
    out.push_str("\n\n");
    out.push_str("import type { TSchema } from \"typebox\";\n\n");
    out.push_str("export interface ToolSchemaDescriptor {\n");
    out.push_str("  boundary_id: string;\n");
    out.push_str("  schema_digest: string;\n");
    out.push_str("  parameters: TSchema;\n");
    out.push_str("}\n\n");

    let enum_values = contracts
        .enums
        .iter()
        .map(|entry| (entry.name.as_str(), entry.values.clone()))
        .collect::<BTreeMap<_, _>>();
    let records = record_items_by_name(contracts);
    let mut descriptors = Vec::new();
    for artifact in contracts
        .artifacts
        .iter()
        .filter(|artifact| artifact.model_produced && artifact.schema.starts_with("planning."))
    {
        let schema = json_schema_for_items(&artifact.items, &records, &enum_values)?;
        let schema_json = serde_json::to_string_pretty(&schema)
            .map_err(|error| CodegenError::Input(format!("json schema emit failed: {error}")))?;
        let canonical = serde_json::to_string(&schema)
            .map_err(|error| CodegenError::Input(format!("json schema digest failed: {error}")))?;
        let digest = sha256_hex(canonical.as_bytes());
        let const_name = format!("{}_TOOL_PARAMETERS", screaming_name(&artifact.name));
        let digest_name = format!("{}_TOOL_SCHEMA_DIGEST", screaming_name(&artifact.name));
        out.push_str(&format!(
            "export const {const_name} = {schema_json} as unknown as TSchema;\n"
        ));
        out.push_str(&format!("export const {digest_name} = \"{digest}\";\n\n"));
        descriptors.push((artifact.schema.clone(), const_name, digest_name));
    }
    out.push_str("export const PLANNING_TOOL_SCHEMAS = {\n");
    for (boundary, const_name, digest_name) in descriptors {
        out.push_str(&format!(
            "  \"{}\": {{ boundary_id: \"{}\", schema_digest: {digest_name}, parameters: {const_name} }},\n",
            escape_ts_string(&boundary),
            escape_ts_string(&boundary)
        ));
    }
    out.push_str("} as const satisfies Record<string, ToolSchemaDescriptor>;\n");
    Ok(out)
}

fn record_items_by_name(contracts: &Contracts) -> BTreeMap<String, Vec<Item>> {
    let mut records = BTreeMap::new();
    for artifact in &contracts.artifacts {
        collect_records(&artifact.items, &mut records);
    }
    records
}

fn collect_records(items: &[Item], records: &mut BTreeMap<String, Vec<Item>>) {
    for item in items {
        match item {
            Item::Record(record) => {
                records.insert(record.name.clone(), record.items.clone());
                collect_records(&record.items, records);
            }
            Item::Group(group) => collect_records(&group.items, records),
            Item::Field(_) | Item::List(_) => {}
        }
    }
}

fn json_schema_for_items(
    items: &[Item],
    records: &BTreeMap<String, Vec<Item>>,
    enum_values: &BTreeMap<&str, Vec<String>>,
) -> Result<JsonValue, CodegenError> {
    let mut properties = JsonMap::new();
    let mut required = Vec::new();
    for item in items {
        match item {
            Item::Field(field) => {
                properties.insert(
                    field.name.clone(),
                    json_schema_for_type(&field.type_id, records, enum_values, field.nullable)?,
                );
                if field.required {
                    required.push(JsonValue::String(field.name.clone()));
                }
            }
            Item::List(list) => {
                let item_schema =
                    json_schema_for_type(&list.item_type, records, enum_values, false)?;
                let mut array = JsonMap::new();
                array.insert("type".to_owned(), JsonValue::String("array".to_owned()));
                array.insert("items".to_owned(), item_schema);
                let mut value = JsonValue::Object(array);
                if list.nullable {
                    value = json!({ "anyOf": [value, { "type": "null" }] });
                }
                properties.insert(list.name.clone(), value);
                if list.required {
                    required.push(JsonValue::String(list.name.clone()));
                }
            }
            Item::Group(group) => {
                properties.insert(
                    group.name.clone(),
                    json_schema_for_items(&group.items, records, enum_values)?,
                );
                if group.required {
                    required.push(JsonValue::String(group.name.clone()));
                }
            }
            Item::Record(_) => {}
        }
    }
    let mut object = JsonMap::new();
    object.insert("type".to_owned(), JsonValue::String("object".to_owned()));
    object.insert("additionalProperties".to_owned(), JsonValue::Bool(true));
    object.insert("properties".to_owned(), JsonValue::Object(properties));
    object.insert("required".to_owned(), JsonValue::Array(required));
    Ok(JsonValue::Object(object))
}

fn json_schema_for_type(
    type_id: &str,
    records: &BTreeMap<String, Vec<Item>>,
    enum_values: &BTreeMap<&str, Vec<String>>,
    nullable: bool,
) -> Result<JsonValue, CodegenError> {
    let mut schema = if let Some(values) = enum_values.get(type_id) {
        json!({ "type": "string", "enum": values })
    } else if let Some(items) = records.get(type_id) {
        json_schema_for_items(items, records, enum_values)?
    } else {
        match type_id {
            "bool" => json!({ "type": "boolean" }),
            "u8" | "u32" | "u64" => json!({ "type": "integer", "minimum": 0 }),
            "object" | "json" | "control_observation" => {
                json!({ "type": "object", "additionalProperties": true })
            }
            _ => json!({ "type": "string" }),
        }
    };
    if nullable {
        schema = json!({ "anyOf": [schema, { "type": "null" }] });
    }
    Ok(schema)
}

fn sha256_hex(data: &[u8]) -> String {
    let digest = Sha256::digest(data);
    let mut out = String::with_capacity(digest.len() * 2);
    for byte in digest {
        out.push_str(&format!("{byte:02x}"));
    }
    out
}

fn required_constant<'a>(contracts: &'a Contracts, key: &str) -> Result<&'a str, CodegenError> {
    contracts
        .constants
        .get(key)
        .map(String::as_str)
        .ok_or_else(|| CodegenError::Input(format!("missing required constant `{key}`")))
}

fn duration_ms(value: &str) -> Result<u64, CodegenError> {
    let seconds = value
        .strip_suffix('s')
        .ok_or_else(|| CodegenError::Input(format!("unsupported duration constant `{value}`")))?;
    let seconds = seconds.parse::<u64>().map_err(|error| {
        CodegenError::Input(format!("invalid duration constant `{value}`: {error}"))
    })?;
    Ok(seconds * 1000)
}

fn emit_shape_tree(
    rust: &mut String,
    typescript: &mut String,
    type_name: &str,
    doc: &str,
    items: &[Item],
    model_facing: bool,
) {
    emit_shape(
        rust,
        typescript,
        type_name,
        doc,
        items,
        type_name,
        model_facing,
    );
    emit_nested_shapes(rust, typescript, type_name, items, model_facing);
}

fn emit_shape(
    rust: &mut String,
    typescript: &mut String,
    type_name: &str,
    doc: &str,
    items: &[Item],
    prefix: &str,
    model_facing: bool,
) {
    rust.push_str(&rust_doc(doc));
    rust.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
    if !model_facing {
        rust.push_str("#[serde(deny_unknown_fields)]\n");
    }
    rust.push_str(&format!("pub struct {type_name} {{\n"));
    typescript.push_str(&format!("export interface {type_name} {{\n"));
    for item in items {
        match item {
            Item::Field(field) => {
                emit_rust_member(
                    rust,
                    &field.name,
                    field.required,
                    field.doc.as_ref(),
                    rust_field_type(&field.type_id, field.required, field.nullable),
                );
                emit_ts_member(
                    typescript,
                    &field.name,
                    field.required,
                    ts_field_type(&field.type_id, field.nullable),
                );
            }
            Item::List(list) => {
                let rust_inner = format!("Vec<{}>", rust_type_ref(&list.item_type));
                emit_rust_member(
                    rust,
                    &list.name,
                    list.required,
                    list.doc.as_ref(),
                    wrap_required_nullable(&rust_inner, list.required, list.nullable),
                );
                let ts_inner = format!("{}[]", ts_type_ref(&list.item_type));
                let ts_ty = if list.nullable {
                    format!("{ts_inner} | null")
                } else {
                    ts_inner
                };
                emit_ts_member(typescript, &list.name, list.required, ts_ty);
            }
            Item::Group(group) => {
                let nested_name = format!("{}{}", prefix, rust_type_name(&group.name));
                emit_rust_member(
                    rust,
                    &group.name,
                    group.required,
                    None,
                    wrap_required_nullable(&nested_name, group.required, false),
                );
                emit_ts_member(typescript, &group.name, group.required, nested_name);
            }
            Item::Record(_) => {}
        }
    }
    rust.push_str("}\n\n");
    typescript.push_str("}\n\n");
}

fn emit_rust_member(
    out: &mut String,
    wire_name: &str,
    required: bool,
    doc: Option<&String>,
    ty: String,
) {
    if let Some(doc) = doc {
        out.push_str(&indent(&rust_doc(doc), "    "));
    }
    for attr in rust_field_attrs(wire_name, !required) {
        out.push_str("    ");
        out.push_str(&attr);
        out.push('\n');
    }
    out.push_str(&format!("    pub {}: {ty},\n", rust_field_name(wire_name)));
}

fn emit_ts_member(out: &mut String, wire_name: &str, required: bool, ty: String) {
    out.push_str(&format!(
        "  {}{}: {ty};\n",
        quote_ts_key(wire_name),
        if required { "" } else { "?" }
    ));
}

fn emit_nested_shapes(
    rust: &mut String,
    typescript: &mut String,
    prefix: &str,
    items: &[Item],
    model_facing: bool,
) {
    for item in items {
        let (nested, doc, nested_items) = match item {
            Item::Group(group) => (
                format!("{}{}", prefix, rust_type_name(&group.name)),
                "Nested generated object.",
                group.items.as_slice(),
            ),
            Item::Record(record) => (
                rust_type_name(&record.name),
                "Generated record item.",
                record.items.as_slice(),
            ),
            Item::Field(_) | Item::List(_) => continue,
        };
        emit_shape(
            rust,
            typescript,
            &nested,
            doc,
            nested_items,
            &nested,
            model_facing,
        );
        emit_nested_shapes(rust, typescript, &nested, nested_items, model_facing);
    }
}

fn emit_prompt(name: &str, admits: &str) -> String {
    format!("<!-- {GENERATED_MARKER} -->\n# {name}\n\n{admits}\n")
}

fn rust_scalar_type(type_id: &str) -> Option<&'static str> {
    match type_id {
        "string" => Some("String"),
        "bool" => Some("bool"),
        "u8" => Some("u8"),
        "u32" => Some("u32"),
        "u64" => Some("u64"),
        "control_observation" | "object" => Some("serde_json::Value"),
        _ => None,
    }
}

fn ts_scalar_type(type_id: &str) -> Option<&'static str> {
    match type_id {
        "string" => Some("string"),
        "bool" => Some("boolean"),
        "u8" | "u32" | "u64" => Some("number"),
        "control_observation" | "object" => Some("JsonObject"),
        _ => None,
    }
}

fn should_emit_newtype(type_id: &str) -> bool {
    rust_scalar_type(type_id).is_none()
}

fn rust_type_ref(type_id: &str) -> String {
    rust_scalar_type(type_id)
        .map(str::to_owned)
        .unwrap_or_else(|| rust_type_name(type_id))
}

fn ts_type_ref(type_id: &str) -> String {
    ts_scalar_type(type_id)
        .map(str::to_owned)
        .unwrap_or_else(|| rust_type_name(type_id))
}

fn rust_field_type(type_id: &str, required: bool, nullable: bool) -> String {
    let inner = rust_type_ref(type_id);
    wrap_required_nullable(&inner, required, nullable)
}

fn wrap_required_nullable(inner: &str, required: bool, nullable: bool) -> String {
    match (required, nullable) {
        (true, true) => format!("Nullable<{inner}>"),
        (true, false) => inner.to_owned(),
        (false, true) | (false, false) => format!("Option<{inner}>"),
    }
}

fn ts_field_type(type_id: &str, nullable: bool) -> String {
    let inner = ts_type_ref(type_id);
    if nullable {
        format!("{inner} | null")
    } else {
        inner
    }
}

fn rust_field_attrs(wire_name: &str, optional: bool) -> Vec<String> {
    let mut attrs = vec![format!(
        "#[serde(rename = \"{}\")]",
        escape_rust_string(wire_name)
    )];
    if optional {
        attrs.push("#[serde(skip_serializing_if = \"Option::is_none\")]".to_owned());
    }
    attrs
}

fn rust_doc(doc: &str) -> String {
    let mut out = String::new();
    for line in doc.lines() {
        out.push_str("/// ");
        out.push_str(line);
        out.push('\n');
    }
    out
}

fn indent(text: &str, prefix: &str) -> String {
    text.lines()
        .map(|line| format!("{prefix}{line}\n"))
        .collect::<String>()
}

fn rust_type_name(input: &str) -> String {
    let mut result = String::new();
    let mut uppercase_next = true;
    for character in input.chars() {
        if character.is_ascii_alphanumeric() {
            if uppercase_next {
                result.push(character.to_ascii_uppercase());
                uppercase_next = false;
            } else {
                result.push(character);
            }
        } else {
            uppercase_next = true;
        }
    }
    if result.is_empty() {
        "GeneratedType".to_owned()
    } else if result
        .chars()
        .next()
        .is_some_and(|character| character.is_ascii_digit())
    {
        format!("N{result}")
    } else {
        result
    }
}

fn rust_variant_name(input: &str) -> String {
    let candidate = rust_type_name(input);
    match candidate.as_str() {
        "Self" | "Super" | "Crate" => format!("{candidate}Value"),
        _ => candidate,
    }
}

fn rust_field_name(input: &str) -> String {
    let mut result = String::new();
    let mut previous_lower = false;
    for character in input.chars() {
        if character == '-' {
            result.push('_');
            previous_lower = false;
        } else if character.is_ascii_uppercase() {
            if previous_lower {
                result.push('_');
            }
            result.push(character.to_ascii_lowercase());
            previous_lower = false;
        } else if character.is_ascii_alphanumeric() {
            result.push(character.to_ascii_lowercase());
            previous_lower = character.is_ascii_lowercase() || character.is_ascii_digit();
        } else {
            result.push('_');
            previous_lower = false;
        }
    }
    if result.is_empty() {
        "field".to_owned()
    } else if result
        .chars()
        .next()
        .is_some_and(|character| character.is_ascii_digit())
    {
        format!("field_{result}")
    } else if is_rust_keyword(&result) {
        format!("{result}_")
    } else {
        result
    }
}

fn is_rust_keyword(input: &str) -> bool {
    matches!(
        input,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
    )
}

fn quote_ts_key(input: &str) -> String {
    if input
        .chars()
        .all(|character| character.is_ascii_alphanumeric() || character == '_')
        && input
            .chars()
            .next()
            .is_some_and(|character| character.is_ascii_alphabetic() || character == '_')
    {
        input.to_owned()
    } else {
        format!("\"{}\"", escape_ts_string(input))
    }
}

fn frame_type_name(frame: &Frame) -> String {
    let prefix = if frame.direction == "host-to-core" {
        "HostToCore"
    } else {
        "CoreToHost"
    };
    format!("{}{}Payload", prefix, rust_type_name(&frame.kind))
}

fn screaming_name(input: &str) -> String {
    let mut result = String::new();
    for character in input.chars() {
        if character.is_ascii_alphanumeric() {
            result.push(character.to_ascii_uppercase());
        } else {
            result.push('_');
        }
    }
    result
}

fn escape_rust_string(input: &str) -> String {
    input.escape_default().to_string()
}

fn escape_ts_string(input: &str) -> String {
    input.replace('\\', "\\\\").replace('"', "\\\"")
}

fn check_outputs(outputs: &[OutputFile]) -> Result<(), CodegenError> {
    let expected: BTreeSet<PathBuf> = outputs.iter().map(|output| output.path.clone()).collect();
    for extra in existing_generated_files()? {
        if !expected.contains(&extra) {
            return Err(CodegenError::Drift(format!(
                "generated output drift: unexpected file {}",
                extra.display()
            )));
        }
    }

    for output in outputs {
        let actual = std::fs::read_to_string(&output.path).map_err(|error| {
            CodegenError::Drift(format!(
                "generated output drift: {} missing or unreadable: {error}",
                output.path.display()
            ))
        })?;
        if actual != output.content {
            return Err(CodegenError::Drift(first_diff(
                &output.path,
                &actual,
                &output.content,
            )));
        }
    }
    Ok(())
}

fn write_outputs(outputs: &[OutputFile]) -> Result<(), CodegenError> {
    let expected: BTreeSet<PathBuf> = outputs.iter().map(|output| output.path.clone()).collect();
    for dir in generated_dirs() {
        if dir.exists() {
            for file in files_under(dir)? {
                if !expected.contains(&file) {
                    std::fs::remove_file(&file).map_err(|error| {
                        CodegenError::Io(format!(
                            "failed to remove stale generated file {}: {error}",
                            file.display()
                        ))
                    })?;
                }
            }
        }
    }
    for output in outputs {
        if let Some(parent) = output.path.parent() {
            std::fs::create_dir_all(parent).map_err(|error| {
                CodegenError::Io(format!(
                    "failed to create generated directory {}: {error}",
                    parent.display()
                ))
            })?;
        }
        std::fs::write(&output.path, output.content.as_bytes()).map_err(|error| {
            CodegenError::Io(format!(
                "failed to write generated file {}: {error}",
                output.path.display()
            ))
        })?;
    }
    Ok(())
}

fn existing_generated_files() -> Result<Vec<PathBuf>, CodegenError> {
    let mut files = Vec::new();
    for dir in generated_dirs() {
        if dir.exists() {
            files.extend(files_under(dir)?);
        }
    }
    files.sort();
    Ok(files)
}

fn generated_dirs() -> Vec<&'static Path> {
    vec![
        Path::new("kernel/src/generated"),
        Path::new("src/generated"),
        Path::new("generated/prompts"),
    ]
}

fn files_under(dir: &Path) -> Result<Vec<PathBuf>, CodegenError> {
    let mut out = Vec::new();
    for entry in std::fs::read_dir(dir).map_err(|error| {
        CodegenError::Io(format!(
            "failed to read directory {}: {error}",
            dir.display()
        ))
    })? {
        let entry = entry.map_err(|error| {
            CodegenError::Io(format!(
                "failed to read directory entry under {}: {error}",
                dir.display()
            ))
        })?;
        let path = entry.path();
        let file_type = entry.file_type().map_err(|error| {
            CodegenError::Io(format!("failed to inspect {}: {error}", path.display()))
        })?;
        if file_type.is_dir() {
            out.extend(files_under(&path)?);
        } else if file_type.is_file() {
            out.push(path);
        }
    }
    out.sort();
    Ok(out)
}

fn first_diff(path: &Path, actual: &str, expected: &str) -> String {
    let actual_lines = actual.lines().collect::<Vec<_>>();
    let expected_lines = expected.lines().collect::<Vec<_>>();
    let max = actual_lines.len().max(expected_lines.len());
    for index in 0..max {
        let actual_line = actual_lines.get(index).copied().unwrap_or("<EOF>");
        let expected_line = expected_lines.get(index).copied().unwrap_or("<EOF>");
        if actual_line != expected_line {
            return format!(
                "generated output drift: {} first differing line {}\n  actual:   {}\n  expected: {}",
                path.display(),
                index + 1,
                actual_line,
                expected_line
            );
        }
    }
    format!("generated output drift: {} differs", path.display())
}
