export { ProcessAdapter, ProcessHandle } from "./process-adapter.js";
export type {
  CaptureObservation,
  PhysicalDiagnostic,
  ProcessCaptureAcquireResult,
  ProcessCaptureSink,
  ProcessCaptureTarget,
  ProcessColdObservation,
  ProcessColdTerminationResult,
  ProcessDescriptor,
  ProcessDescriptorRequest,
  ProcessDescriptorResult,
  ProcessGraceWaiter,
  ProcessIdentityInspector,
  ProcessGroupObservation,
  ProcessLifecycleObservation,
  ProcessObservation,
  ProcessObserveResult,
  ProcessOutputObservation,
  ProcessOutputReadRequest,
  ProcessOutputReadResult,
  ProcessSignal,
  ProcessSignalResult,
  ProcessStartRequest,
  ProcessStartResult,
  ProcessTerminationObservation,
  ProcessTerminationResult,
  SignalDeliveryObservation,
} from "./types.js";
