/* GENERATED by policy-root/generate-aggregates.ts. DO NOT EDIT. */
import { childIntentCapsule } from "./child.capsule.js";
import { childObservationCapsule } from "./child.capsule.js";
import { clockIntentCapsule } from "./clock.capsule.js";
import { clockObservationCapsule } from "./clock.capsule.js";
import { gitIntentCapsule } from "./git.capsule.js";
import { gitObservationCapsule } from "./git.capsule.js";
import { secretsIntentCapsule } from "./secrets.capsule.js";
import { secretsObservationCapsule } from "./secrets.capsule.js";
import { storeIntentCapsule } from "./store.capsule.js";
import { storeObservationCapsule } from "./store.capsule.js";
import { workspaceIntentCapsule } from "./workspace.capsule.js";
import { workspaceObservationCapsule } from "./workspace.capsule.js";

export {
  childIntentCapsule,
  childObservationCapsule,
  clockIntentCapsule,
  clockObservationCapsule,
  gitIntentCapsule,
  gitObservationCapsule,
  secretsIntentCapsule,
  secretsObservationCapsule,
  storeIntentCapsule,
  storeObservationCapsule,
  workspaceIntentCapsule,
  workspaceObservationCapsule,
};

export const portContractCapsules = Object.freeze([
  childIntentCapsule,
  childObservationCapsule,
  clockIntentCapsule,
  clockObservationCapsule,
  gitIntentCapsule,
  gitObservationCapsule,
  secretsIntentCapsule,
  secretsObservationCapsule,
  storeIntentCapsule,
  storeObservationCapsule,
  workspaceIntentCapsule,
  workspaceObservationCapsule,
]);
