#!/usr/bin/env bash
#
# child-runtime-thinness.sh — child delivery runtime boundary gate.
#
# Sibling of host-thinness.sh, scoped to child-runtime/. That directory holds the
# runtime loaded inside a SPAWNED CHILD Pi agent (launched `--no-extensions -e
# <addon>`). It is NOT the operator-session Host, so it is not counted against
# HOST_BUDGET — but it is emphatically not ungoverned, which is what this gate is.
#
# The Host's risk is DECIDING. This component's risk is INFERRING.
#
#     THE CHILD RUNTIME INFERS NOTHING.
#
# It mechanically enforces an allowlist Core already decided and cryptographically
# pinned, using opaque byte equality with zero parsing. Every way it could stop
# being that is a banned term below: re-implementing shell semantics instead of
# comparing approved command bytes, fuzzy/glob path matching instead of exact set
# membership, recursive directory creation (the mkdir trap), silent fallback, and
# outright guessing. Escape hatches are banned because a confinement check that is
# `as any`-cast or `@ts-ignore`d is not a check.
#
# Two checks, identical in mechanism to host-thinness.sh:
#   1. SIZE      — child runtime <= CHILD_RUNTIME_BUDGET LOC.
#   2. SEMANTICS — child runtime source contains no inference/decision vocabulary.
#
# Usage:
#     scripts/gates/child-runtime-thinness.sh
#     scripts/gates/child-runtime-thinness.sh --root DIR
#
# Exit codes:
#     0  child runtime is bounded and inference-free
#     1  violation (HALT AND REPORT)
#     2  usage/environment error
#
set -euo pipefail

# Budget raises are NOT a routine escape hatch. CHILD_RUNTIME_BUDGET must equal
# the `to` value of the final entry in child-runtime-budget-ledger.json, and that
# entry must carry a measured before/after and an itemized justification. The gate
# below verifies this, so raising the number without recording WHY is itself a
# gate failure. The budget is seeded at the exact measured actual with ZERO
# headroom: unearned slack is what lets someone park new files here unnoticed.
readonly CHILD_RUNTIME_BUDGET=578
readonly BUDGET_LEDGER="scripts/gates/child-runtime-budget-ledger.json"
readonly GENERATED_MARKER='@generated by codegen'
readonly GENERATED_SCAN_LINES=5

# Decision vocabulary, copied verbatim from host-thinness.sh BANNED_DECISION as a
# floor. A child runtime that starts deriving run state or issuing verdicts has
# become a second orchestrator just as surely as a fat Host would.
# Substring, case-insensitive: semantics leak through identifiers.
readonly -a BANNED_DECISION=(
  # state derivation — Core owns fold(events)
  'fold(' 'applyEvent' 'deriveState' 'computeState' 'reduceEvents'
  # workflow vocabulary — D76 §5.3 lives in workflow.kdl, interpreted by Core
  'forward-validating' 'forward-ready' 'forward-integrated' 'forward-blocked'
  'deep-validating' 'closure-needs-fix' 'repair-queued' 'release-queued'
  'laneState' 'candidateState' 'runPhase' 'nextState' 'transitionTo'
  # scheduling — Core owns readiness/capacity/dispatch
  'parallel_cap' 'parallelCap' 'planNextDispatch' 'selectReadyLane' 'tieBreak'
  # integration — Core owns the queue, merge, and CAS
  'mergeCandidate' 'updateRef' 'compareAndSwap' 'threeWayMerge' 'resolveConflict'
  # verdicts — Core owns acceptance
  'FORWARD_READY' 'FORWARD_BLOCKED' 'NEEDS_FIX' 'acceptDelivery' 'verdictFor'
  'localAcceptance' 'findings.length' 'validationFindings'
  '"pass" | "fail"' "'pass' | 'fail'" '"pass" : "fail"' "'pass' : 'fail'"
  # role/prompt selection — Core owns the registry and renderer
  'selectRole' 'renderPrompt' 'buildPrompt' 'chooseMode' 'contextManifest'

  # ---- child-runtime-specific: INFERENCE, not decision ----
  # shell semantics — approved commands are compared as opaque bytes. The moment
  # this file splits, tokenizes, or re-executes a command string it is modelling
  # a shell, and its model will disagree with the shell that actually runs.
  'shlex' 'shellSplit' 'splitCommand' 'parseCommand' 'tokenizeCommand'
  'execSync' 'spawnSync' 'eval(' 'new Function'
  # fuzzy matching — confinement is exact set membership, never pattern matching
  'minimatch' 'micromatch' 'new RegExp('
  # the mkdir trap — recursive creation silently manufactures the very parent
  # directories whose topology this runtime is supposed to be validating
  'recursive: true' 'recursive:true'
  # silent fallback — a confinement check that degrades is not a check
  'bestEffort' 'lenient' 'permissive' 'skipCheck' 'allowAny' 'allowAll' '|| true'
  # inference — this component is allowed to know, never to estimate
  'heuristic' 'infer' 'guess' 'approximate'
  # escape hatches — an unchecked cast voids the enforcement it is applied to
  '@ts-ignore' '@ts-expect-error' 'as any' 'TODO' 'FIXME' 'HACK'
  # prefix authority — banned, with a counted exception documented below
  '.startsWith('
)

# Narrow, documented exceptions. Each entry is TERM<TAB>MAX_OCCURRENCES: the term
# stays banned, and the gate still fails if the count moves in EITHER direction,
# so a new occurrence cannot hide behind an existing legitimate one.
#
# '.startsWith(' — prefix tests are doctrinally interesting because prefix
# authority ("this path starts with the worktree, therefore it is allowed") is a
# classic confinement bypass. All four occurrences here are the SAFE direction:
#   * one selects planning boundary ids for tool registration (not a path);
#   * three are the canonical `path.relative(...)` escape test, `relative
#     .startsWith("..")`, which REJECTS on match rather than granting on match.
# No occurrence tests a path against the worktree prefix to grant access; that
# authority comes from exact membership in policy.allowedAbsolutePaths.
#
# Raised 3 -> 4 when the mkdir/ENOENT confinement fix was integrated: the fourth
# is ancestorDirectoryChain()'s `parentRelative.startsWith("..")`, the same
# reject-on-match escape test applied to an approved file's parent chain. Verified
# by the orchestrator: `grep -cE '\.startsWith\(\s*(policy\.)?worktree|\.startsWith\(\s*root'`
# returns 0, i.e. no grant-direction prefix test exists in this file.
# Pinned at exactly 4 so a fifth — or a grant-direction rewrite of these — trips
# the gate. The pin fails in BOTH directions: a drop to 3 means this written
# rationale has gone stale and must be re-reviewed.
readonly -a BANNED_EXCEPTIONS=(
  $'.startsWith(\t4'
)

usage() {
  cat >&2 <<'EOF'
usage: child-runtime-thinness.sh [--root DIR]

  Verifies the spawned-child delivery runtime stays within its LOC budget and
  contains no inference/decision vocabulary. Sources are child-runtime/**/*.ts
  excluding generated files.

  --root DIR   treat DIR as the package root (default: script's ../../)
EOF
  exit 2
}

root=""
while [ $# -gt 0 ]; do
  case "$1" in
    --root)
      [ $# -ge 2 ] || usage
      root="$2"; shift 2 ;;
    -h|--help) usage ;;
    *) printf 'child-runtime-thinness.sh: unknown argument: %s\n' "$1" >&2; usage ;;
  esac
done

if [ -z "$root" ]; then
  script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
  root="$(cd -- "$script_dir/../.." && pwd)"
fi

[ -d "$root" ] || { printf 'child-runtime-thinness.sh: no such root: %s\n' "$root" >&2; exit 2; }

# Unlike the Host gate, absence is NOT vacuously fine: this directory is a named
# payload path and a missing one means the relocation silently regressed.
runtime_dir="$root/child-runtime"
if [ ! -d "$runtime_dir" ]; then
  printf 'child-runtime-thinness.sh: child-runtime/ absent — expected the child delivery runtime here\n' >&2
  exit 2
fi

files=()
while IFS= read -r f; do
  head -n "$GENERATED_SCAN_LINES" "$f" 2>/dev/null | grep -qF "$GENERATED_MARKER" && continue
  files+=("$f")
done < <(find -L "$runtime_dir" -type f \( -name '*.ts' -o -name '*.mts' \) \
           -not -path '*/node_modules/*' -not -path '*/dist/*' | LC_ALL=C sort)

if [ "${#files[@]}" -eq 0 ]; then
  printf 'child-runtime-thinness.sh: no non-generated child runtime sources found\n' >&2
  exit 2
fi

strip_comments() {
  awk '
    { sub(/\r$/, "") }
    /^[[:space:]]*\/\*.*\*\/[[:space:]]*$/ { next }
    /^[[:space:]]*\/\*/ { inblock = 1; next }
    inblock { if ($0 ~ /\*\//) { inblock = 0 } next }
    /^[[:space:]]*$/ { next }
    /^[[:space:]]*\/\// { next }
    { printf "%d:%s\n", NR, $0 }
  ' "$1"
}

exception_allowance() {
  local term="$1" row key
  for row in "${BANNED_EXCEPTIONS[@]}"; do
    key="${row%%$'\t'*}"
    if [ "$key" = "$term" ]; then printf '%s' "${row#*$'\t'}"; return 0; fi
  done
  printf '%s' ''
}

total=0
violations=0
declare -a all_code=()

for f in "${files[@]}"; do
  rel="${f#"$root"/}"
  code="$(strip_comments "$f")"
  [ -n "$code" ] || continue

  n="$(printf '%s\n' "$code" | grep -c '' || true)"
  total=$((total + n))
  all_code+=("$rel"$'\t'"$code")
done

for term in "${BANNED_DECISION[@]}"; do
  allowance="$(exception_allowance "$term")"
  term_hits=0
  hit_lines=()
  for blob in "${all_code[@]}"; do
    rel="${blob%%$'\t'*}"
    code="${blob#*$'\t'}"
    while IFS= read -r hit; do
      [ -n "$hit" ] || continue
      ln="${hit%%:*}"
      content="${hit#*:}"
      term_hits=$((term_hits + 1))
      hit_lines+=("$(printf '  INFERENCE %s:%s  [%s]\n    %s' "$rel" "$ln" "$term" \
        "$(printf '%s' "$content" | sed 's/^[[:space:]]*//')")")
    done < <(printf '%s\n' "$code" | grep -iF "$term" || true)
  done

  if [ -n "$allowance" ]; then
    # Documented exception: the count must match EXACTLY. More means a new
    # occurrence; fewer means the documented rationale is stale.
    if [ "$term_hits" -ne "$allowance" ]; then
      printf '  EXCEPTION-DRIFT  [%s] expected exactly %s documented occurrence(s), found %d\n' \
        "$term" "$allowance" "$term_hits" >&2
      for line in "${hit_lines[@]}"; do printf '%s\n' "$line" >&2; done
      violations=$((violations + 1))
    fi
    continue
  fi

  if [ "$term_hits" -gt 0 ]; then
    for line in "${hit_lines[@]}"; do printf '%s\n' "$line" >&2; done
    violations=$((violations + term_hits))
  fi
done

ledger_path="$root/$BUDGET_LEDGER"
if [ ! -f "$ledger_path" ]; then
  printf 'child-runtime-thinness.sh: missing budget ledger: %s\n' "$BUDGET_LEDGER" >&2
  exit 2
fi
ledger_to="$(python3 -c '
import json,sys
rows=json.load(open(sys.argv[1]))
if not isinstance(rows,list) or not rows: raise SystemExit("ledger must be a non-empty array")
last=rows[-1]
for key in ("from","to","actualBefore","actualAfter","sourceDelta","justification"):
    if key not in last: raise SystemExit(f"ledger entry missing {key}")
if not str(last["justification"]).strip(): raise SystemExit("ledger justification must not be empty")
prev=None
for row in rows:
    if prev is not None and row["from"] != prev: raise SystemExit("ledger from/to chain is discontinuous")
    prev=row["to"]
print(last["to"])
' "$ledger_path")" || { printf 'child-runtime-thinness.sh: invalid budget ledger\n' >&2; exit 2; }
if [ "$ledger_to" != "$CHILD_RUNTIME_BUDGET" ]; then
  printf 'child-runtime-thinness.sh: CHILD_RUNTIME_BUDGET=%s does not match ledger final to=%s — record the change and WHY in %s\n' \
    "$CHILD_RUNTIME_BUDGET" "$ledger_to" "$BUDGET_LEDGER" >&2
  exit 2
fi

files_n="${#files[@]}"
printf 'child-runtime-thinness.sh: files=%d loc=%d budget=%d inferences=%d\n' \
  "$files_n" "$total" "$CHILD_RUNTIME_BUDGET" "$violations"

failed=0

if [ "$total" -gt "$CHILD_RUNTIME_BUDGET" ]; then
  cat >&2 <<EOF

child-runtime-thinness.sh: CHILD RUNTIME BUDGET EXCEEDED — $total LOC, budget $CHILD_RUNTIME_BUDGET.

  This budget carries ZERO headroom by design. If the growth is a genuine
  confinement check, measure it and record a ledger entry saying so. Do NOT
  raise the number to make room, and do NOT park unrelated files here.
EOF
  failed=1
fi

if [ "$violations" -gt 0 ]; then
  cat >&2 <<EOF

child-runtime-thinness.sh: $violations INFERENCE VIOLATION(S).

  THE CHILD RUNTIME INFERS NOTHING. It enforces an allowlist Core already
  decided and pinned, by opaque byte equality with zero parsing. It must not
  model shell semantics, pattern-match paths, create directories recursively,
  degrade to a fallback, guess, or cast its own checks away.

  Do NOT delete banned terms to make this pass. If an occurrence is genuinely
  legitimate, keep the term banned and add a narrow, documented, counted entry
  to BANNED_EXCEPTIONS explaining exactly why.
EOF
  failed=1
fi

[ "$failed" -eq 0 ] || exit 1

printf 'child-runtime-thinness.sh: PASS — child runtime is bounded (%d LOC) and inference-free\n' "$total"
exit 0
