#!/usr/bin/env bash
#
# host-thinness.sh — D78 host boundary gate (DoD S7).
#
# Pi loads extensions as TypeScript modules, so the Autopilot Host must be JS.
# That is unavoidable. What IS avoidable is the Host slowly re-acquiring
# semantics until it becomes a second orchestrator that disagrees with Core.
#
# This gate enforces the D78 rule:
#
#     THE HOST DECIDES NOTHING.
#
# It translates Pi events into Core requests and Core effects into Pi actions.
# Every semantic decision — run state, lane readiness, merge admissibility,
# validation verdicts, scheduling, role selection — belongs to Core.
#
# Two checks:
#   1. SIZE      — Host <= 1200 LOC (separate from the Core budget).
#   2. SEMANTICS — Host source contains no decision vocabulary.
#
# The single sanctioned exception is the scoped fail-closed guard default (D78
# §3.3): inside Autopilot's authority, Core unavailability/timeouts DENY. The
# Host may also route out-of-scope Pi tools around Core. That scope predicate is
# routing, not semantic verdict logic, and is pinned by negative tests.
#
# Usage:
#     scripts/gates/host-thinness.sh
#     scripts/gates/host-thinness.sh --root DIR
#
# Exit codes:
#     0  host is thin and decision-free
#     1  violation (HALT AND REPORT)
#     2  usage/environment error
#
set -euo pipefail

# Budget raises are NOT a routine escape hatch. HOST_BUDGET must equal the `to`
# value of the final entry in host-budget-ledger.json, and that entry must carry
# a measured before/after and an itemized justification. The gate below verifies
# this, so raising the number without recording WHY is itself a gate failure.
readonly HOST_BUDGET=1123
readonly BUDGET_LEDGER="scripts/gates/host-budget-ledger.json"
readonly GENERATED_MARKER='@generated by codegen'
readonly GENERATED_SCAN_LINES=5

# Decision vocabulary the Host must never contain. Substring, case-insensitive:
# semantics leak through identifiers (`computeLaneReadiness`), not just words.
readonly -a BANNED_DECISION=(
  # state derivation — Core owns fold(events)
  'fold(' 'applyEvent' 'deriveState' 'computeState' 'reduceEvents'
  # workflow vocabulary — D76 §5.3 lives in workflow.kdl, interpreted by Core
  'forward-validating' 'forward-ready' 'forward-integrated' 'forward-blocked'
  'deep-validating' 'closure-needs-fix' 'repair-queued' 'release-queued'
  'laneState' 'candidateState' 'runPhase' 'nextState' 'transitionTo'
  # scheduling — Core owns readiness/capacity/dispatch
  'parallel_cap' 'parallelCap' 'planNextDispatch' 'selectReadyLane' 'tieBreak'
  # integration — Core owns the queue, merge, and CAS
  'mergeCandidate' 'updateRef' 'compareAndSwap' 'threeWayMerge' 'resolveConflict'
  # verdicts — Core owns acceptance
  'FORWARD_READY' 'FORWARD_BLOCKED' 'NEEDS_FIX' 'acceptDelivery' 'verdictFor'
  'localAcceptance' 'findings.length' 'validationFindings'
  '"pass" | "fail"' "'pass' | 'fail'" '"pass" : "fail"' "'pass' : 'fail'"
  # role/prompt selection — Core owns the registry and renderer
  'selectRole' 'renderPrompt' 'buildPrompt' 'chooseMode' 'contextManifest'
)

usage() {
  cat >&2 <<'EOF'
usage: host-thinness.sh [--root DIR]

  Verifies the Pi-extension Host stays <= 1200 LOC and contains no decision
  logic (DoD S7). Host sources are src/**/*.ts excluding generated files.

  --root DIR   treat DIR as the package root (default: script's ../../)
EOF
  exit 2
}

root=""
while [ $# -gt 0 ]; do
  case "$1" in
    --root)
      [ $# -ge 2 ] || usage
      root="$2"; shift 2 ;;
    -h|--help) usage ;;
    *) printf 'host-thinness.sh: unknown argument: %s\n' "$1" >&2; usage ;;
  esac
done

if [ -z "$root" ]; then
  script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
  root="$(cd -- "$script_dir/../.." && pwd)"
fi

[ -d "$root" ] || { printf 'host-thinness.sh: no such root: %s\n' "$root" >&2; exit 2; }

host_dir="$root/src"
if [ ! -d "$host_dir" ]; then
  printf 'host-thinness.sh: src/ absent (pre-W3) — vacuously thin\n'
  exit 0
fi

files=()
while IFS= read -r f; do
  head -n "$GENERATED_SCAN_LINES" "$f" 2>/dev/null | grep -qF "$GENERATED_MARKER" && continue
  files+=("$f")
done < <(find -L "$host_dir" -type f \( -name '*.ts' -o -name '*.mts' \) \
           -not -path '*/node_modules/*' -not -path '*/dist/*' | LC_ALL=C sort)

if [ "${#files[@]}" -eq 0 ]; then
  printf 'host-thinness.sh: no non-generated host sources — vacuously thin\n'
  exit 0
fi

strip_comments() {
  awk '
    { sub(/\r$/, "") }
    /^[[:space:]]*\/\*.*\*\/[[:space:]]*$/ { next }
    /^[[:space:]]*\/\*/ { inblock = 1; next }
    inblock { if ($0 ~ /\*\//) { inblock = 0 } next }
    /^[[:space:]]*$/ { next }
    /^[[:space:]]*\/\// { next }
    { printf "%d:%s\n", NR, $0 }
  ' "$1"
}

total=0
violations=0

for f in "${files[@]}"; do
  rel="${f#"$root"/}"
  code="$(strip_comments "$f")"
  [ -n "$code" ] || continue

  n="$(printf '%s\n' "$code" | grep -c '' || true)"
  total=$((total + n))

  for term in "${BANNED_DECISION[@]}"; do
    while IFS= read -r hit; do
      [ -n "$hit" ] || continue
      ln="${hit%%:*}"
      content="${hit#*:}"
      printf '  DECISION  %s:%s  [%s]\n    %s\n' \
        "$rel" "$ln" "$term" \
        "$(printf '%s' "$content" | sed 's/^[[:space:]]*//')" >&2
      violations=$((violations + 1))
    done < <(printf '%s\n' "$code" | grep -iF "$term" || true)
  done
done

ledger_path="$root/$BUDGET_LEDGER"
if [ ! -f "$ledger_path" ]; then
  printf 'host-thinness.sh: missing budget ledger: %s\n' "$BUDGET_LEDGER" >&2
  exit 2
fi
ledger_to="$(python3 -c '
import json,sys
rows=json.load(open(sys.argv[1]))
if not isinstance(rows,list) or not rows: raise SystemExit("ledger must be a non-empty array")
last=rows[-1]
for key in ("from","to","actualBefore","actualAfter","sourceDelta","justification"):
    if key not in last: raise SystemExit(f"ledger entry missing {key}")
if not str(last["justification"]).strip(): raise SystemExit("ledger justification must not be empty")
prev=None
for row in rows:
    if prev is not None and row["from"] != prev: raise SystemExit("ledger from/to chain is discontinuous")
    prev=row["to"]
print(last["to"])
' "$ledger_path")" || { printf 'host-thinness.sh: invalid budget ledger\n' >&2; exit 2; }
if [ "$ledger_to" != "$HOST_BUDGET" ]; then
  printf 'host-thinness.sh: HOST_BUDGET=%s does not match ledger final to=%s — record the raise and WHY in %s\n' \
    "$HOST_BUDGET" "$ledger_to" "$BUDGET_LEDGER" >&2
  exit 2
fi

files_n="${#files[@]}"
printf 'host-thinness.sh: files=%d loc=%d budget=%d decisions=%d\n' \
  "$files_n" "$total" "$HOST_BUDGET" "$violations"

failed=0

if [ "$total" -gt "$HOST_BUDGET" ]; then
  cat >&2 <<EOF

host-thinness.sh: HOST BUDGET EXCEEDED — $total LOC, budget $HOST_BUDGET.

  The Host is a transport adapter, not a component. Move logic into Core.
  Do NOT raise the budget.
EOF
  failed=1
fi

if [ "$violations" -gt 0 ]; then
  cat >&2 <<EOF

host-thinness.sh: $violations DECISION VIOLATION(S).

  D78: THE HOST DECIDES NOTHING. It forwards Pi events to Core and applies
  Core effects. Run state, lane readiness, merge admissibility, verdicts,
  scheduling, and role/prompt selection all belong to Core.

  The only sanctioned Host decision is the scoped fail-closed guard default:
  inside Autopilot's authority, Core unavailability/timeouts DENY (D78 §3.3).

  Do NOT delete banned terms to make this pass.
EOF
  failed=1
fi

[ "$failed" -eq 0 ] || exit 1

printf 'host-thinness.sh: PASS — host is thin (%d LOC) and decision-free\n' "$total"
exit 0
