#!/usr/bin/env bash
#
# kernel-purity.sh — D77 kernel neutrality gate (DoD S4, F1).
#
# The kernel is a generic interpreter. It must know nothing about Autopilot's
# domain: no role names, no lane/candidate state names, no Git, no Pi SDK, no
# filesystem paths. All domain knowledge lives in declarative data
# (workflow.kdl / contracts.kdl / roles/) and all IO lives behind `Platform`.
#
# If this gate fails, the data/code boundary has leaked and the offending logic
# belongs in data or a driver — not in the kernel.
#
# Two independent checks:
#   1. DOMAIN VOCABULARY  (DoD S4) — kernel must not name domain concepts.
#   2. IMPURITY           (DoD F1) — kernel must not touch clock/fs/process/RNG.
#
# Usage:
#     scripts/gates/kernel-purity.sh
#     scripts/gates/kernel-purity.sh --root DIR
#
# Exit codes:
#     0  kernel is pure
#     1  violation found (HALT AND REPORT)
#     2  usage/environment error
#
set -euo pipefail

readonly GENERATED_MARKER='@generated by codegen'
readonly GENERATED_SCAN_LINES=5

# --- banned domain vocabulary (DoD S4) --------------------------------------
# Regexes are matched case-insensitively against non-comment kernel source.
# These are the D76 §2.3 role ids, §5.3 state names, and infrastructure nouns.
readonly -a BANNED_DOMAIN=(
  # D76 §2.3 role ids
  'implementer' 'validator' 'fixer' 'bughunter' 'allocator' 'scout'
  'curator' 'extractor' 'resolver' 'compiler' 'synthesizer' 'onboard'
  # D76 §5.3 lane / candidate state names
  'forward-validating' 'forward-ready' 'forward-integrated' 'forward-blocked'
  'deep-validating' 'closure-needs-fix' 'repair-queued' 'release-queued'
  # domain nouns
  'lane' 'candidate' 'worktree' 'run-main' 'sparse'
  # external systems the kernel must never name
  'git' 'pi-sdk' 'pi_sdk' 'bg_run' 'codex' 'openai' 'anthropic'
)

# --- banned impurity (DoD F1) -----------------------------------------------
# The kernel is pure: it returns Effect descriptions, it never performs IO.
readonly -a BANNED_IMPURITY=(
  'SystemTime::now'
  'Instant::now'
  'Utc::now'
  'std::fs'
  'std::process'
  'Command::new'
  'rand::'
  'thread_rng'
  'random('
  'env::var'
  'println!'
  'eprintln!'
)

usage() {
  cat >&2 <<'EOF'
usage: kernel-purity.sh [--root DIR]

  Verifies kernel/**/*.rs contains no domain vocabulary (DoD S4)
  and no impure operations (DoD F1).

  --root DIR   treat DIR as the workspace root (default: script's ../../)
EOF
  exit 2
}

root=""
while [ $# -gt 0 ]; do
  case "$1" in
    --root)
      [ $# -ge 2 ] || usage
      root="$2"; shift 2 ;;
    -h|--help) usage ;;
    *) printf 'kernel-purity.sh: unknown argument: %s\n' "$1" >&2; usage ;;
  esac
done

if [ -z "$root" ]; then
  script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
  root="$(cd -- "$script_dir/../.." && pwd)"
fi

[ -d "$root" ] || { printf 'kernel-purity.sh: no such root: %s\n' "$root" >&2; exit 2; }

kernel_dir="$root/kernel"
if [ ! -d "$kernel_dir" ]; then
  printf 'kernel-purity.sh: kernel/ absent (pre-W1) — vacuously pure\n'
  exit 0
fi

# --- gather non-generated kernel sources ------------------------------------

files=()
while IFS= read -r f; do
  head -n "$GENERATED_SCAN_LINES" "$f" 2>/dev/null | grep -qF "$GENERATED_MARKER" && continue
  files+=("$f")
done < <(find "$kernel_dir" -type f -name '*.rs' -not -path '*/target/*' | LC_ALL=C sort)

if [ "${#files[@]}" -eq 0 ]; then
  printf 'kernel-purity.sh: no non-generated kernel sources — vacuously pure\n'
  exit 0
fi

# strip_comments FILE — emit only code lines (comments/blanks removed), keeping
# original line numbers as "NNN:content" so violations can be reported exactly.
strip_comments() {
  awk '
    { sub(/\r$/, "") }
    /^[[:space:]]*\/\*.*\*\/[[:space:]]*$/ { next }
    /^[[:space:]]*\/\*/ { inblock = 1; next }
    inblock { if ($0 ~ /\*\//) { inblock = 0 } next }
    /^[[:space:]]*$/ { next }
    /^[[:space:]]*\/\// { next }
    { printf "%d:%s\n", NR, $0 }
  ' "$1"
}

violations=0

report() {
  # report KIND FILE LINE TERM CONTENT
  printf '  %-9s %s:%s  [%s]\n    %s\n' "$1" "$2" "$3" "$4" "$5" >&2
  violations=$((violations + 1))
}

for f in "${files[@]}"; do
  rel="${f#"$root"/}"
  code="$(strip_comments "$f")"
  [ -n "$code" ] || continue

  # --- check 1: domain vocabulary (case-insensitive, SUBSTRING match) ---
  # Deliberately substring, not word-boundary: `spawn_implementer`,
  # `lane_is_ready`, and `GitRef` must all trip the gate. Domain vocabulary
  # embedded inside an identifier is exactly how the boundary leaks, so the
  # match must be as permissive as the leak. Comments are already stripped,
  # so prose is unaffected.
  for term in "${BANNED_DOMAIN[@]}"; do
    while IFS= read -r hit; do
      [ -n "$hit" ] || continue
      ln="${hit%%:*}"
      content="${hit#*:}"
      report "DOMAIN" "$rel" "$ln" "$term" "$(printf '%s' "$content" | sed 's/^[[:space:]]*//')"
    done < <(printf '%s\n' "$code" | grep -iF "$term" || true)
  done

  # --- check 2: impurity (literal, case-sensitive) ---
  for term in "${BANNED_IMPURITY[@]}"; do
    while IFS= read -r hit; do
      [ -n "$hit" ] || continue
      ln="${hit%%:*}"
      content="${hit#*:}"
      report "IMPURITY" "$rel" "$ln" "$term" "$(printf '%s' "$content" | sed 's/^[[:space:]]*//')"
    done < <(printf '%s\n' "$code" | grep -F "$term" || true)
  done
done

files_n="${#files[@]}"

if [ "$violations" -gt 0 ]; then
  cat >&2 <<EOF

kernel-purity.sh: $violations VIOLATION(S) across $files_n kernel file(s).

  DOMAIN   — the kernel named an Autopilot concept. Move it into declarative
             data (workflow.kdl / contracts.kdl / roles/).
  IMPURITY — the kernel touched the world directly. Move it behind the
             Platform trait into a driver.

  D77 halt condition. Do NOT widen the banned list to make this pass.
EOF
  exit 1
fi

printf 'kernel-purity.sh: PASS — %d kernel file(s), no domain vocabulary, no impurity\n' "$files_n"
exit 0
