#!/usr/bin/env bash
#
# loc.sh — D77 structural budget gate (DoD S1, S2).
#
# The kernel LOC budget is the W1 kill-switch. It is NOT a quality dial: when
# the budget is exceeded the correct response is to halt and re-cut the
# data/code boundary, never to raise the ceiling. This script is therefore an
# independent referee and must not be edited to make a wave pass.
#
# Usage:
#     scripts/gates/loc.sh kernel     # DoD S1 — must be <= 2000
#     scripts/gates/loc.sh core       # DoD S2 — must be <= 6500
#     scripts/gates/loc.sh tooling    # DoD S2b — must be <= 2000
#     scripts/gates/loc.sh all        # report combined total against 8500
#     scripts/gates/loc.sh --root DIR kernel
#
# Counting rule (deliberately conservative — it over-counts rather than
# under-counts, so the gate can never be gamed by formatting):
#   - counts .rs files only (declarative data is NOT code and is not counted);
#   - EXCLUDES blank lines;
#   - EXCLUDES whole-line `//` and `//!` comments and whole-line `/* */`;
#   - INCLUDES everything else, including `#[derive]`, `use`, and braces;
#   - EXCLUDES `tests/` trees and `#[cfg(test)]` modules are NOT excluded
#     (test code inside a source file counts against the budget — this is
#     intentional; it discourages hiding logic in test-gated modules).
#   - EXCLUDES generated files, which must carry the exact marker line
#     `// @generated by codegen` within their first 5 lines.
#
# Exit codes:
#     0  budget satisfied
#     1  enforced budget exceeded  (HALT AND REPORT — do not raise the budget)
#     2  usage/environment error
#
set -euo pipefail

readonly KERNEL_BUDGET=2000
readonly CORE_BUDGET=6500
readonly TOOLING_BUDGET=2000
readonly ALL_BUDGET=8500
readonly GENERATED_MARKER='@generated by codegen'
readonly GENERATED_SCAN_LINES=5

usage() {
  cat >&2 <<'EOF'
usage: loc.sh [--root DIR] <kernel|core|tooling|all>

  kernel   count kernel/**/*.rs        (DoD S1, budget 2000)
  core     count kernel + drivers      (DoD S2 shipped Core, budget 6500)
  tooling  count codegen + modelcheck  (DoD S2b build-time tooling, budget 2000)
  all      count all four crates       (combined reporting budget 8500 = core 6500 + tooling 2000)

  --root DIR   treat DIR as the workspace root (default: script's ../../)
EOF
  exit 2
}

# --- argument parsing -------------------------------------------------------

root=""
scope=""

while [ $# -gt 0 ]; do
  case "$1" in
    --root)
      [ $# -ge 2 ] || usage
      root="$2"
      shift 2
      ;;
    kernel|core|tooling|all)
      [ -z "$scope" ] || usage
      scope="$1"
      shift
      ;;
    -h|--help)
      usage
      ;;
    *)
      printf 'loc.sh: unknown argument: %s\n' "$1" >&2
      usage
      ;;
  esac
done

[ -n "$scope" ] || usage

if [ -z "$root" ]; then
  script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
  root="$(cd -- "$script_dir/../.." && pwd)"
fi

if [ ! -d "$root" ]; then
  printf 'loc.sh: root directory does not exist: %s\n' "$root" >&2
  exit 2
fi

# --- scope -> directories ---------------------------------------------------

case "$scope" in
  kernel)
    dirs=(kernel)
    budget=$KERNEL_BUDGET
    budget_note=""
    enforce_budget=1
    ;;
  core)
    dirs=(kernel drivers)
    budget=$CORE_BUDGET
    budget_note=""
    enforce_budget=1
    ;;
  tooling)
    dirs=(codegen modelcheck)
    budget=$TOOLING_BUDGET
    budget_note=""
    enforce_budget=1
    ;;
  all)
    dirs=(kernel drivers codegen modelcheck)
    budget=$ALL_BUDGET
    budget_note=" (combined core 6500 + tooling 2000; reported only, not enforced; enforce precise scopes with core/tooling)"
    enforce_budget=0
    ;;
esac

# --- collect source files ---------------------------------------------------
# Missing directories are not an error: early waves legitimately have only a
# subset present. A scope whose directories are ALL missing counts as 0, which
# is correct for W0 (no Rust yet) and harmless later.

files=()
for d in "${dirs[@]}"; do
  full="$root/$d"
  [ -d "$full" ] || continue
  while IFS= read -r f; do
    files+=("$f")
  done < <(find "$full" -type f -name '*.rs' -not -path '*/target/*' | LC_ALL=C sort)
done

# --- count ------------------------------------------------------------------

total=0
counted_files=0
skipped_generated=0

for f in "${files[@]:-}"; do
  [ -n "${f:-}" ] || continue

  if head -n "$GENERATED_SCAN_LINES" "$f" 2>/dev/null | grep -qF "$GENERATED_MARKER"; then
    skipped_generated=$((skipped_generated + 1))
    continue
  fi

  n="$(
    awk '
      # strip trailing CR so CRLF files count identically
      { sub(/\r$/, "") }

      # whole-line block comment: /* ... */ on one line
      /^[[:space:]]*\/\*.*\*\/[[:space:]]*$/ { next }

      # block comment open -> enter skip mode
      /^[[:space:]]*\/\*/ { inblock = 1; next }
      inblock {
        if ($0 ~ /\*\//) { inblock = 0 }
        next
      }

      # blank
      /^[[:space:]]*$/ { next }

      # whole-line // or //! or /// comment
      /^[[:space:]]*\/\// { next }

      { n++ }
      END { print n + 0 }
    ' "$f"
  )"

  total=$((total + n))
  counted_files=$((counted_files + 1))
done

# --- report -----------------------------------------------------------------

printf 'loc.sh: scope=%s files=%d generated_skipped=%d loc=%d budget=%d%s\n' \
  "$scope" "$counted_files" "$skipped_generated" "$total" "$budget" "$budget_note"

if [ "$enforce_budget" -eq 1 ] && [ "$total" -gt "$budget" ]; then
  cat >&2 <<EOF

loc.sh: BUDGET EXCEEDED — $scope is $total LOC, budget is $budget.

  D77 halt condition. The correct response is to HALT AND REPORT, then move
  logic out of code and into declarative data (workflow.kdl / contracts.kdl /
  role data) or into a driver.

  Do NOT raise the budget. Do NOT edit this script.
EOF
  exit 1
fi

exit 0
