#!/usr/bin/env bash
#
# no-inference.sh — D77 state-authority gate (DoD B4, Closure B).
#
# The event log is the ONLY authority: state = fold(events). Nothing may infer
# state from a filename, mtime, directory listing, file-existence check, or
# process fact. An artifact on disk with no corresponding event does not exist.
#
# This is the gate that prevents the dev-orchestrator's failure mode, where
# state was reconstructed from artifacts + ledger pairing. That produced
# 3,740 LOC of inference, 30+ `ambiguous-legacy-progress` sites, and 13
# consecutive live blockers (BUG-159..171).
#
# Scope: kernel/ and drivers/ state-reading paths. Drivers MAY touch the
# filesystem (that is their job) but MUST NOT use what they find to decide
# what state a run is in — so the banned constructs below are those that turn
# a filesystem observation into a state decision.
#
# Usage:
#     scripts/gates/no-inference.sh
#     scripts/gates/no-inference.sh --root DIR
#
# Exit codes:
#     0  no state inference found
#     1  inference found (HALT AND REPORT)
#     2  usage/environment error
#
set -euo pipefail

readonly GENERATED_MARKER='@generated by codegen'
readonly GENERATED_SCAN_LINES=5

# Concepts that turn a filesystem/time/process observation into a state
# decision. Each concept is fixed-string matched, case-sensitive, without a
# trailing call marker: matching `exists` deliberately catches both
# `entry.exists()` and the bare field/identifier form `entry.exists`.
readonly -a BANNED_INFERENCE_CONCEPTS=(
  # existence-as-authority
  'exists'
  'try_exists'
  'is_file'
  'is_dir'
  # time-as-authority
  'modified'
  'mtime'
  'created'
  'accessed'
  'metadata'
  # listing-as-authority
  'read_dir'
  'glob'
  'walkdir'
  'DirEntry'
  # name-as-authority
  'file_stem'
  'extension'
  'file_name'
  'ends_with'
  'starts_with'
  # process-as-authority
  'kill'
  'is_alive'
  'pid_exists'
  # ordering-as-authority
  'latest'
  'most_recent'
)

# Genuine patterns. Every entry is validated before any source is scanned.
readonly -a BANNED_INFERENCE_PATTERNS=(
  # ordering-as-authority
  'sort_by_key\(\|.*modified'
)

# Files exempted from the listing/existence rules because their entire purpose
# is disposable-cache management or archival cleanup, which are explicitly NOT
# state decisions. Each exemption must be justified here, and each exempted
# file must still never use what it finds to set run/lane/candidate state.
readonly -a EXEMPT_SUFFIXES=(
  'drivers/fs/cleanup.rs'      # safe-archive removal after close (D76 §10)
  'drivers/fs/cache.rs'        # state.json disposable cache (Closure B)
)

usage() {
  cat >&2 <<'EOF'
usage: no-inference.sh [--root DIR]

  Verifies kernel/ and drivers/ never infer state from filenames, mtimes,
  directory listings, existence checks, or process facts (DoD B4).

  --root DIR   treat DIR as the workspace root (default: script's ../../)
EOF
  exit 2
}

root=""
while [ $# -gt 0 ]; do
  case "$1" in
    --root)
      [ $# -ge 2 ] || usage
      root="$2"; shift 2 ;;
    -h|--help) usage ;;
    *) printf 'no-inference.sh: unknown argument: %s\n' "$1" >&2; usage ;;
  esac
done

if [ -z "$root" ]; then
  script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
  root="$(cd -- "$script_dir/../.." && pwd)"
fi

[ -d "$root" ] || { printf 'no-inference.sh: no such root: %s\n' "$root" >&2; exit 2; }

validate_pattern_terms() {
  local term status err
  for term in "${BANNED_INFERENCE_PATTERNS[@]}"; do
    if err="$(printf '' | LC_ALL=C grep -E -- "$term" 2>&1 >/dev/null)"; then
      status=0
    else
      status=$?
    fi

    if [ "$status" -ge 2 ]; then
      printf 'no-inference.sh: malformed BANNED_INFERENCE_PATTERNS entry: %s\n' "$term" >&2
      [ -z "$err" ] || printf '  grep: %s\n' "$err" >&2
      exit 2
    fi
  done
}

validate_pattern_terms

is_exempt() {
  local rel="$1" suffix
  for suffix in "${EXEMPT_SUFFIXES[@]}"; do
    case "$rel" in
      *"$suffix") return 0 ;;
    esac
  done
  return 1
}

files=()
for d in kernel drivers; do
  full="$root/$d"
  [ -d "$full" ] || continue
  while IFS= read -r f; do
    head -n "$GENERATED_SCAN_LINES" "$f" 2>/dev/null | grep -qF "$GENERATED_MARKER" && continue
    files+=("$f")
  done < <(find "$full" -type f -name '*.rs' -not -path '*/target/*' | LC_ALL=C sort)
done

if [ "${#files[@]}" -eq 0 ]; then
  printf 'no-inference.sh: no kernel/ or drivers/ sources (pre-W1) — vacuously clean\n'
  exit 0
fi

strip_comments() {
  awk '
    { sub(/\r$/, "") }
    /^[[:space:]]*\/\*.*\*\/[[:space:]]*$/ { next }
    /^[[:space:]]*\/\*/ { inblock = 1; next }
    inblock { if ($0 ~ /\*\//) { inblock = 0 } next }
    /^[[:space:]]*$/ { next }
    /^[[:space:]]*\/\// { next }
    { printf "%d:%s\n", NR, $0 }
  ' "$1"
}

violations=0
exempted=0
scanned=0

scan_term() {
  local matcher="$1" term="$2" rel="$3" code="$4"
  local matches status hit ln content

  case "$matcher" in
    literal)
      if matches="$(printf '%s\n' "$code" | LC_ALL=C grep -F -- "$term" 2>/dev/null)"; then
        status=0
      else
        status=$?
      fi
      ;;
    pattern)
      if matches="$(printf '%s\n' "$code" | LC_ALL=C grep -E -- "$term" 2>/dev/null)"; then
        status=0
      else
        status=$?
      fi
      ;;
    *)
      printf 'no-inference.sh: internal error: unknown matcher: %s\n' "$matcher" >&2
      exit 2
      ;;
  esac

  case "$status" in
    0) ;;
    1) return 0 ;;
    *)
      printf 'no-inference.sh: grep failed while scanning %s for %s term [%s] (exit %d)\n' \
        "$rel" "$matcher" "$term" "$status" >&2
      exit 2
      ;;
  esac

  while IFS= read -r hit; do
    [ -n "$hit" ] || continue
    ln="${hit%%:*}"
    content="${hit#*:}"
    printf '  %s:%s  [%s]\n    %s\n' \
      "$rel" "$ln" "$term" \
      "$(printf '%s' "$content" | sed 's/^[[:space:]]*//')" >&2
    violations=$((violations + 1))
  done <<< "$matches"
}

for f in "${files[@]}"; do
  rel="${f#"$root"/}"

  if is_exempt "$rel"; then
    exempted=$((exempted + 1))
    continue
  fi

  scanned=$((scanned + 1))
  code="$(strip_comments "$f")"
  [ -n "$code" ] || continue

  for term in "${BANNED_INFERENCE_CONCEPTS[@]}"; do
    scan_term literal "$term" "$rel" "$code"
  done
  for term in "${BANNED_INFERENCE_PATTERNS[@]}"; do
    scan_term pattern "$term" "$rel" "$code"
  done
done

if [ "$violations" -gt 0 ]; then
  cat >&2 <<EOF

no-inference.sh: $violations STATE-INFERENCE VIOLATION(S) across $scanned file(s).

  The event log is the only authority: state = fold(events). A filename,
  mtime, directory listing, existence check, or process fact must never
  decide what state a run, lane, or candidate is in.

  If the code genuinely needs disposable-cache or safe-cleanup filesystem
  access, add an explicit, justified entry to EXEMPT_SUFFIXES — and prove the
  file still never sets run/lane/candidate state.

  D77 halt condition. Do NOT delete banned terms to make this pass.
EOF
  exit 1
fi

printf 'no-inference.sh: PASS — %d file(s) scanned, %d exempted, no state inference\n' \
  "$scanned" "$exempted"
exit 0
