#!/usr/bin/env node
/*
 * readable-source.mjs — static recurrence gate for source readability/accounting.
 *
 * This gate catches the classes observed in the codegen readability audit without
 * changing LOC budgets: identity macro packing, rustfmt suppression, hidden data
 * Rust includes, non-KDL include_str templates, large escaped runtime strings, and
 * overlong handwritten production lines. Generated files are skipped only when a
 * generated marker appears in the first five lines.
 */
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const GENERATED_MARKER = /@generated by codegen/u;
const GENERATED_SCAN_LINES = 5;
const LONG_LINE_LIMIT = 120;
const ESCAPED_NEWLINE_LIMIT = 20;
const DEFAULT_MAX_FINDINGS = 1000;
const SCAN_ROOTS = ['codegen/src', 'modelcheck/src', 'kernel/src', 'drivers/src', 'src', 'child-runtime'];
const SOURCE_EXTENSIONS = new Set(['.rs', '.ts', '.mts', '.js']);
const PRUNED_COMPONENTS = new Set(['.git', 'target', 'node_modules', 'dist']);
const SKIPPED_PRODUCTION_COMPONENTS = new Set(['tests']);

// Tiny documented allowlists. These are exact/package-relative and must not be
// widened by directory. KDL data includes are validated by semantic pattern below.
const ALLOWED_PLAIN_TEXT_INCLUDES = new Set(['README.md', 'LICENSE']);

// Digest-binding source includes. This is NOT a plain-text asset allowlist: the
// included bytes are hashed into CHILD_ADDON_DIGEST, and
// drivers::runner::child_addon_digest_for_path independently re-derives that
// digest from disk and REFUSES TO SPAWN a child agent on mismatch. The
// include_str! is what binds the compiled binary to the exact bytes of the child
// delivery runtime, so removing it is a supply-chain regression, not a cleanup.
//
// Every entry is matched by EXACT RESOLVED PATH (never substring), is scoped to
// one calling file, and is count-pinned. Widening by directory, glob, or count is
// prohibited. The pin is BIDIRECTIONAL: if the target exists on disk but the
// calling file no longer includes it, that is reported as
// `missing_digest_binding_include`, so weakening the digest binding turns this
// gate RED rather than silently passing.
// Per-class expected counts. This is a RATCHET, not a suppression: the gate still
// exits 1 while findings > 0, and every count below is reported. Its purpose is to
// make the count drift-detectable in BOTH directions, because a permanently-red
// gate with no ratchet cannot tell a new regression from accepted debt — which is
// exactly how a new violation class (non_kdl_include_str) reached certification
// unnoticed through four prior reviews.
//
// A count going UP is an unreviewed regression. A count going DOWN is also a
// finding: it means debt was paid and this ledger must be lowered deliberately, so
// the numbers ratchet down over time instead of silently eroding upward.
//
// overlong_handwritten_source is 258 against a certified baseline of 244. The
// surviving +14 lines are CANDIDATE-INTRODUCED, OPERATOR-ACCEPTED debt (not
// pre-existing) and remain itemized in every gate report. This ratchet was lowered
// from 260 after codegen's list-schema expression and the ambient ReadOperations
// declaration were structurally wrapped without changing runtime bytes. Other debt
// remains constrained by flush Host/child LOC
// budgets or exact prompt/authority bytes. Rustfmt is authoritative for Rust line
// breaking and `cargo fmt --check` is green, so any surviving >120-column Rust line
// is one rustfmt will not break automatically.
const EXPECTED_CLASS_COUNTS = {
  codegen_escaped_newline_string: 3,
  hidden_data_rust_include: 1,
  identity_macro: 7,
  immediate_identity_invocation: 5,
  overlong_handwritten_source: 258,
  rustfmt_suppression: 1,
};

const ALLOWED_DIGEST_BINDING_INCLUDES = [
  {
    rel: 'codegen/src/emit.rs',
    target: 'child-runtime/child-extension-runtime.ts',
    expect: 1,
    reason:
      'CHILD_ADDON_DIGEST = sha256(wrapper \0 runtime); drivers/src/runner/mod.rs ' +
      're-derives it from disk and refuses to spawn a child on mismatch.',
  },
];
const DECLARATIVE_LONG_LINE_ALLOWLIST = [
  {
    rel: 'codegen/src/contracts.rs',
    pattern: /^    "authority-class .* validation-scope"$/u,
    reason: 'declarative built-in scalar vocabulary',
  },
  {
    rel: 'codegen/src/contracts.rs',
    pattern: /^    "as break const continue .* while"$/u,
    reason: 'declarative Rust keyword vocabulary',
  },
];

function usage() {
  process.stderr.write(`usage: readable-source.mjs [--root DIR] [--max-findings N]\n`);
  process.exit(2);
}

let root = '';
let maxFindings = DEFAULT_MAX_FINDINGS;
for (let i = 2; i < process.argv.length; i += 1) {
  const arg = process.argv[i];
  if (arg === '--root') {
    root = process.argv[++i] ?? '';
    if (root === '') usage();
  } else if (arg === '--max-findings') {
    const text = process.argv[++i] ?? '';
    maxFindings = Number.parseInt(text, 10);
    if (!Number.isSafeInteger(maxFindings) || maxFindings < 1) usage();
  } else if (arg === '-h' || arg === '--help') {
    usage();
  } else {
    process.stderr.write(`readable-source.mjs: unknown argument: ${arg}\n`);
    usage();
  }
}

if (root === '') {
  root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
}
if (!existsSync(root)) {
  process.stderr.write(`readable-source.mjs: root directory does not exist: ${root}\n`);
  process.exit(2);
}

function extension(path) {
  const dot = path.lastIndexOf('.');
  return dot === -1 ? '' : path.slice(dot);
}

function hasComponent(rel, components) {
  return rel.split(/[\\/]+/u).some((part) => components.has(part));
}

function shouldPrune(abs) {
  return abs.split(sep).some((part) => PRUNED_COMPONENTS.has(part));
}

function collect(dir, out) {
  if (!existsSync(dir) || shouldPrune(dir)) return;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const abs = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (!PRUNED_COMPONENTS.has(entry.name)) collect(abs, out);
    } else if (entry.isFile() && SOURCE_EXTENSIONS.has(extension(entry.name))) {
      out.push(abs);
    }
  }
}

function isGenerated(lines) {
  return lines.slice(0, GENERATED_SCAN_LINES).some((line) => GENERATED_MARKER.test(line));
}

function isWholeLineCommentOrBlank(line) {
  return /^\s*(?:$|\/\/|\/\*|\*)/u.test(line);
}

function report(findings, rel, line, klass, detail, source = '') {
  findings.push({ rel, line, klass, detail, source: source.trim().slice(0, 180) });
}

function allowedLongLine(rel, line) {
  return DECLARATIVE_LONG_LINE_ALLOWLIST.some(
    (entry) => entry.rel === rel && entry.pattern.test(line),
  );
}

function escapedNewlineCount(line) {
  return (line.match(/\\n/gu) ?? []).length;
}

function invocationText(lines, startIndex) {
  let text = '';
  let balance = 0;
  let sawParen = false;
  for (let i = startIndex; i < Math.min(lines.length, startIndex + 16); i += 1) {
    const line = lines[i];
    text += `${line}\n`;
    for (const char of line) {
      if (char === '(') {
        balance += 1;
        sawParen = true;
      } else if (char === ')') {
        balance -= 1;
      }
    }
    if (sawParen && balance <= 0) break;
  }
  return text;
}

function allowedKdlInclude(text) {
  return /(?:^|["'`/])(?:\.\.\/)*data\/[^"'`)]+\.kdl\b/u.test(text);
}

function escapeRegex(text) {
  return text.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&');
}

// Exact resolved-path match, scoped to the calling file. Resolving the include
// argument relative to the caller's directory is what makes this non-widenable:
// a '../../'-prefixed literal only matches if it genuinely resolves to the
// declared package-relative target, so moving either file breaks the match
// rather than silently continuing to pass.
const digestBindingSeen = [];
function digestBindingInclude(rel, text) {
  const arg = text.match(/\binclude_str!\s*\(\s*["'`]([^"'`]+)["'`]/u);
  if (!arg) return undefined;
  const resolved = join(dirname(rel), arg[1]).split(sep).join('/');
  const normalized = resolved.split('/').reduce((acc, part) => {
    if (part === '.' || part === '') return acc;
    if (part === '..') { acc.pop(); return acc; }
    acc.push(part); return acc;
  }, []).join('/');
  return ALLOWED_DIGEST_BINDING_INCLUDES.find((e) => e.rel === rel && e.target === normalized);
}

function allowedPlainTextInclude(text) {
  return [...ALLOWED_PLAIN_TEXT_INCLUDES].some((rel) => {
    const quotedPath = new RegExp('["\'`]' + escapeRegex(rel) + '["\'`]', 'u');
    return quotedPath.test(text);
  });
}

function scanFile(abs, findings) {
  const rel = relative(root, abs).split(sep).join('/');
  if (hasComponent(rel, SKIPPED_PRODUCTION_COMPONENTS)) return { skipped: false, generated: false };
  const text = readFileSync(abs, 'utf8').replace(/\r\n/gu, '\n');
  const lines = text.split('\n');
  if (isGenerated(lines)) return { skipped: true, generated: true };

  const identityMacros = [];

  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i];
    const lineNo = i + 1;
    if (isWholeLineCommentOrBlank(line)) continue;

    const identity = line.match(/\bmacro_rules!\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{[^\n]*\$\(\$t:tt\)\*[^\n]*=>[^\n]*\$\(\$t\)\*[^\n]*\}/u);
    if (identity) {
      identityMacros.push({ name: identity[1], line: lineNo });
      report(findings, rel, lineNo, 'identity_macro', `macro ${identity[1]} forwards token trees unchanged`, line);
    }

    if (/rustfmt_skip|rustfmt::skip/u.test(line)) {
      report(findings, rel, lineNo, 'rustfmt_suppression', 'rustfmt suppression is forbidden in production source', line);
    }

    if (line.includes('include!')) {
      const includeText = invocationText(lines, i);
      if (/\binclude!\s*\(/u.test(includeText) && /(?:^|["'`/])(?:\.\.\/)*data\/[^"'`)]+\.rs\b/u.test(includeText)) {
        report(findings, rel, lineNo, 'hidden_data_rust_include', 'include!(...data/*.rs) hides compiled Rust outside counted source', includeText.replace(/\s+/gu, ' '));
      }
    }

    if (line.includes('include_str!')) {
      const includeText = invocationText(lines, i);
      if (/\binclude_str!\s*\(/u.test(includeText) && !allowedKdlInclude(includeText) && !allowedPlainTextInclude(includeText)) {
        if (digestBindingInclude(rel, includeText)) digestBindingSeen.push(`${rel}\u0000${digestBindingInclude(rel, includeText).target}`);
        else report(findings, rel, lineNo, 'non_kdl_include_str', 'include_str! is allowed only for data/*.kdl or exact documented plain text', includeText.replace(/\s+/gu, ' '));
      }
    }

    if (rel.startsWith('codegen/src/') && rel.endsWith('.rs')) {
      const count = escapedNewlineCount(line);
      if (count > ESCAPED_NEWLINE_LIMIT) {
        report(findings, rel, lineNo, 'codegen_escaped_newline_string', `line contains ${count} escaped newlines`, line);
      }
    }

    if (line.length > LONG_LINE_LIMIT && !allowedLongLine(rel, line)) {
      report(findings, rel, lineNo, 'overlong_handwritten_source', `line length ${line.length} exceeds ${LONG_LINE_LIMIT}`, line);
    }
  }

  for (const macro of identityMacros) {
    for (let j = macro.line; j < Math.min(lines.length, macro.line + 6); j += 1) {
      const candidate = lines[j];
      if (isWholeLineCommentOrBlank(candidate)) continue;
      if (new RegExp(`^\\s*${macro.name}\\s*!`, 'u').test(candidate)) {
        report(findings, rel, j + 1, 'immediate_identity_invocation', `identity macro ${macro.name} is invoked immediately after its definition`, candidate);
      }
      break;
    }
  }

  return { skipped: false, generated: false };
}

const files = [];
for (const scanRoot of SCAN_ROOTS) collect(join(root, scanRoot), files);
files.sort((a, b) => relative(root, a).localeCompare(relative(root, b)));

const findings = [];
let generatedSkipped = 0;
let scanned = 0;
for (const file of files) {
  const result = scanFile(file, findings);
  if (result.generated) generatedSkipped += 1;
  else if (!result.skipped) scanned += 1;
}

// Bidirectional enforcement of the digest-binding includes. An entry that is
// declared but absent (while its target still exists on disk) means the compiled
// binary has stopped attesting those bytes. That must fail loudly here rather
// than pass quietly as "one fewer finding".
for (const entry of ALLOWED_DIGEST_BINDING_INCLUDES) {
  if (!existsSync(join(root, entry.target))) continue;
  const seen = digestBindingSeen.filter((k) => k === `${entry.rel}\u0000${entry.target}`).length;
  if (seen !== entry.expect) {
    report(
      findings,
      entry.rel,
      0,
      seen === 0 ? 'missing_digest_binding_include' : 'digest_binding_include_drift',
      `expected exactly ${entry.expect} include_str! of ${entry.target} in ${entry.rel}, found ${seen} (${entry.reason})`,
      '',
    );
  }
}

const byClass = new Map();
for (const finding of findings) byClass.set(finding.klass, (byClass.get(finding.klass) ?? 0) + 1);

// Bidirectional class-count drift. Reported to stderr and forced non-zero exit;
// deliberately NOT added to `findings` so the reported per-class numbers stay a
// truthful census rather than counting themselves.
let classDrift = 0;
for (const klass of new Set([...Object.keys(EXPECTED_CLASS_COUNTS), ...byClass.keys()])) {
  const expected = EXPECTED_CLASS_COUNTS[klass] ?? 0;
  const actual = byClass.get(klass) ?? 0;
  if (actual === expected) continue;
  classDrift += 1;
  const direction = actual > expected ? 'REGRESSION (new unreviewed findings)' : 'IMPROVED (lower this ledger deliberately)';
  process.stderr.write(`  CLASS-DRIFT  ${klass}  expected ${expected}, found ${actual} — ${direction}\n`);
}

process.stdout.write(`readable-source.mjs: files=${scanned} generated_skipped=${generatedSkipped} findings=${findings.length}`);
for (const [klass, count] of [...byClass.entries()].sort()) process.stdout.write(` ${klass}=${count}`);
process.stdout.write('\n');

for (const finding of findings.slice(0, maxFindings)) {
  process.stderr.write(`  ${finding.klass}  ${finding.rel}:${finding.line}  ${finding.detail}\n`);
  if (finding.source) process.stderr.write(`    ${finding.source}\n`);
}
if (findings.length > maxFindings) {
  process.stderr.write(`  ... ${findings.length - maxFindings} additional findings omitted by --max-findings=${maxFindings}\n`);
}

if (classDrift > 0) {
  process.stderr.write(`\nreadable-source.mjs: ${classDrift} class-count drift(s). Every count in EXPECTED_CLASS_COUNTS is\n  pinned in both directions. Do NOT edit a number to make this pass: an increase is an\n  unreviewed regression, and a decrease must be recorded as debt deliberately paid down.\n`);
  process.exit(1);
}
if (findings.length > 0) process.exit(1);
process.exit(0);
