/* GENERATED by policy-root/generate-aggregates.ts. DO NOT EDIT. */
import { commandCapsule } from "./command.capsule.js";
import { domainFactCapsule } from "./domain-fact.capsule.js";
import { evidenceFactCapsule } from "./evidence-fact.capsule.js";
import { findingCapsule } from "./finding.capsule.js";
import { ingestDecisionCapsule } from "./ingest-decision.capsule.js";
import { journalRecordCapsule } from "./journal-record.capsule.js";
import { stimulusCapsule } from "./stimulus.capsule.js";
import { terminalOutcomeCapsule } from "./terminal-outcome.capsule.js";
import { toolResultCapsule } from "./tool-result.capsule.js";
import { workItemCapsule } from "./work-item.capsule.js";

export {
  commandCapsule,
  domainFactCapsule,
  evidenceFactCapsule,
  findingCapsule,
  ingestDecisionCapsule,
  journalRecordCapsule,
  stimulusCapsule,
  terminalOutcomeCapsule,
  toolResultCapsule,
  workItemCapsule,
};

export const protocolCapsules = Object.freeze([
  commandCapsule,
  domainFactCapsule,
  evidenceFactCapsule,
  findingCapsule,
  ingestDecisionCapsule,
  journalRecordCapsule,
  stimulusCapsule,
  terminalOutcomeCapsule,
  toolResultCapsule,
  workItemCapsule,
]);
